// Generated by scripts/generate_jcvm_api.py. Do not edit.
// Source: Java Card 3.0.5 export files, read from the development kit. Tokens are what a CAP file uses to name an imported class, field or method.

/// One method an imported package declares, named by its token.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ApiMethod {
    pub token: u8,
    pub name: &'static str,
    pub descriptor: &'static str,
    pub is_static: bool,
    /// Whether the token belongs to the static namespace, which constructors
    /// share with static methods even though they are instance methods.
    pub static_token: bool,
}

/// One class an imported package declares.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ApiClass {
    pub token: u8,
    pub name: &'static str,
    pub is_interface: bool,
    pub methods: &'static [ApiMethod],
}

/// One package an applet may import.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ApiPackage {
    pub aid: &'static [u8],
    pub name: &'static str,
    /// The version the export file declares, which an import has to be satisfied by.
    pub major: u8,
    pub minor: u8,
    pub classes: &'static [ApiClass],
}

const METHODS_A0000000620001_0: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
];

const METHODS_A0000000620001_1: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
];

const METHODS_A0000000620001_2: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
];

const METHODS_A0000000620001_3: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
];

const METHODS_A0000000620001_4: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
];

const METHODS_A0000000620001_5: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
];

const METHODS_A0000000620001_6: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
];

const METHODS_A0000000620001_7: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
];

const METHODS_A0000000620001_8: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
];

const METHODS_A0000000620001_9: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
];

const METHODS_A0000000620001_10: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
];

const METHODS_A0000000620001_11: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
];

const CLASSES_A0000000620001: [ApiClass; 12] = [
    ApiClass { token: 0, name: "java/lang/Object", is_interface: false, methods: &METHODS_A0000000620001_0 },
    ApiClass { token: 1, name: "java/lang/Throwable", is_interface: false, methods: &METHODS_A0000000620001_1 },
    ApiClass { token: 2, name: "java/lang/Exception", is_interface: false, methods: &METHODS_A0000000620001_2 },
    ApiClass { token: 3, name: "java/lang/RuntimeException", is_interface: false, methods: &METHODS_A0000000620001_3 },
    ApiClass { token: 4, name: "java/lang/IndexOutOfBoundsException", is_interface: false, methods: &METHODS_A0000000620001_4 },
    ApiClass { token: 5, name: "java/lang/ArrayIndexOutOfBoundsException", is_interface: false, methods: &METHODS_A0000000620001_5 },
    ApiClass { token: 6, name: "java/lang/NegativeArraySizeException", is_interface: false, methods: &METHODS_A0000000620001_6 },
    ApiClass { token: 7, name: "java/lang/NullPointerException", is_interface: false, methods: &METHODS_A0000000620001_7 },
    ApiClass { token: 8, name: "java/lang/ClassCastException", is_interface: false, methods: &METHODS_A0000000620001_8 },
    ApiClass { token: 9, name: "java/lang/ArithmeticException", is_interface: false, methods: &METHODS_A0000000620001_9 },
    ApiClass { token: 10, name: "java/lang/SecurityException", is_interface: false, methods: &METHODS_A0000000620001_10 },
    ApiClass { token: 11, name: "java/lang/ArrayStoreException", is_interface: false, methods: &METHODS_A0000000620001_11 },
];

const METHODS_A0000000620101_18: [ApiMethod; 1] = [
    ApiMethod { token: 0, name: "uninstall", descriptor: "()V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_0: [ApiMethod; 0] = [
];

const METHODS_A0000000620101_17: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "select", descriptor: "(Z)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "deselect", descriptor: "(Z)V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_1: [ApiMethod; 4] = [
    ApiMethod { token: 0, name: "check", descriptor: "([BSB)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getTriesRemaining", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "isValidated", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "reset", descriptor: "()V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_19: [ApiMethod; 8] = [
    ApiMethod { token: 0, name: "check", descriptor: "([BSB)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getTriesRemaining", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "isValidated", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "reset", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "update", descriptor: "([BSB)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getTryLimit", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "setTryLimit", descriptor: "(B)V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "setTriesRemaining", descriptor: "(B)V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_20: [ApiMethod; 9] = [
    ApiMethod { token: 0, name: "check", descriptor: "([BSB)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getTriesRemaining", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "isValidated", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "reset", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "update", descriptor: "([BSB)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getTryLimit", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "setTryLimit", descriptor: "(B)V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "setTriesRemaining", descriptor: "(B)V", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "decrementTriesRemaining", descriptor: "()B", is_static: false, static_token: false },
];

const METHODS_A0000000620101_2: [ApiMethod; 0] = [
];

const METHODS_A0000000620101_6: [ApiMethod; 7] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "([BSB)V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "RIDEquals", descriptor: "(Ljavacard/framework/AID;)Z", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "equals", descriptor: "([BSB)Z", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "getBytes", descriptor: "([BS)B", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "partialEquals", descriptor: "([BSB)Z", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getPartialBytes", descriptor: "(S[BSB)B", is_static: false, static_token: false },
];

const METHODS_A0000000620101_5: [ApiMethod; 5] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "(S)V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "throwIt", descriptor: "(S)V", is_static: true, static_token: true },
    ApiMethod { token: 1, name: "getReason", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "setReason", descriptor: "(S)V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_8: [ApiMethod; 24] = [
    ApiMethod { token: 0, name: "abortTransaction", descriptor: "()V", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "beginTransaction", descriptor: "()V", is_static: true, static_token: true },
    ApiMethod { token: 2, name: "commitTransaction", descriptor: "()V", is_static: true, static_token: true },
    ApiMethod { token: 3, name: "getAID", descriptor: "()Ljavacard/framework/AID;", is_static: true, static_token: true },
    ApiMethod { token: 4, name: "getAppletShareableInterfaceObject", descriptor: "(Ljavacard/framework/AID;B)Ljavacard/framework/Shareable;", is_static: true, static_token: true },
    ApiMethod { token: 5, name: "getMaxCommitCapacity", descriptor: "()S", is_static: true, static_token: true },
    ApiMethod { token: 6, name: "getPreviousContextAID", descriptor: "()Ljavacard/framework/AID;", is_static: true, static_token: true },
    ApiMethod { token: 7, name: "getTransactionDepth", descriptor: "()B", is_static: true, static_token: true },
    ApiMethod { token: 8, name: "getUnusedCommitCapacity", descriptor: "()S", is_static: true, static_token: true },
    ApiMethod { token: 9, name: "getVersion", descriptor: "()S", is_static: true, static_token: true },
    ApiMethod { token: 10, name: "isTransient", descriptor: "(Ljava/lang/Object;)B", is_static: true, static_token: true },
    ApiMethod { token: 11, name: "lookupAID", descriptor: "([BSB)Ljavacard/framework/AID;", is_static: true, static_token: true },
    ApiMethod { token: 12, name: "makeTransientBooleanArray", descriptor: "(SB)[Z", is_static: true, static_token: true },
    ApiMethod { token: 13, name: "makeTransientByteArray", descriptor: "(SB)[B", is_static: true, static_token: true },
    ApiMethod { token: 14, name: "makeTransientObjectArray", descriptor: "(SB)[Ljava/lang/Object;", is_static: true, static_token: true },
    ApiMethod { token: 15, name: "makeTransientShortArray", descriptor: "(SB)[S", is_static: true, static_token: true },
    ApiMethod { token: 16, name: "getAvailableMemory", descriptor: "(B)S", is_static: true, static_token: true },
    ApiMethod { token: 17, name: "isObjectDeletionSupported", descriptor: "()Z", is_static: true, static_token: true },
    ApiMethod { token: 18, name: "requestObjectDeletion", descriptor: "()V", is_static: true, static_token: true },
    ApiMethod { token: 19, name: "getAssignedChannel", descriptor: "()B", is_static: true, static_token: true },
    ApiMethod { token: 20, name: "isAppletActive", descriptor: "(Ljavacard/framework/AID;)Z", is_static: true, static_token: true },
    ApiMethod { token: 21, name: "makeGlobalArray", descriptor: "(BS)Ljava/lang/Object;", is_static: true, static_token: true },
    ApiMethod { token: 22, name: "getAvailableMemory", descriptor: "([SSB)V", is_static: true, static_token: true },
];

const METHODS_A0000000620101_12: [ApiMethod; 5] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "(S)V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "throwIt", descriptor: "(S)V", is_static: true, static_token: true },
    ApiMethod { token: 1, name: "getReason", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "setReason", descriptor: "(S)V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_9: [ApiMethod; 10] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "(BB)V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "check", descriptor: "([BSB)Z", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getTriesRemaining", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "getValidatedFlag", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "isValidated", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "reset", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "resetAndUnblock", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "setValidatedFlag", descriptor: "(Z)V", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "update", descriptor: "([BSB)V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_21: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "buildOwnerPIN", descriptor: "(BBB)Ljavacard/framework/PIN;", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
];

const METHODS_A0000000620101_3: [ApiMethod; 11] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "install", descriptor: "([BSB)V", is_static: true, static_token: true },
    ApiMethod { token: 1, name: "register", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "reSelectingApplet", descriptor: "()Z", is_static: true, static_token: true },
    ApiMethod { token: 2, name: "register", descriptor: "([BSB)V", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "selectingApplet", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "deselect", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getShareableInterfaceObject", descriptor: "(Ljavacard/framework/AID;B)Ljavacard/framework/Shareable;", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "select", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "process", descriptor: "(Ljavacard/framework/APDU;)V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_10: [ApiMethod; 25] = [
    ApiMethod { token: 0, name: "getInBlockSize", descriptor: "()S", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getOutBlockSize", descriptor: "()S", is_static: true, static_token: true },
    ApiMethod { token: 1, name: "getBuffer", descriptor: "()[B", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getProtocol", descriptor: "()B", is_static: true, static_token: true },
    ApiMethod { token: 2, name: "getNAD", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "waitExtension", descriptor: "()V", is_static: true, static_token: true },
    ApiMethod { token: 3, name: "receiveBytes", descriptor: "(S)S", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "getCurrentAPDU", descriptor: "()Ljavacard/framework/APDU;", is_static: true, static_token: true },
    ApiMethod { token: 4, name: "sendBytes", descriptor: "(SS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getCurrentAPDUBuffer", descriptor: "()[B", is_static: true, static_token: true },
    ApiMethod { token: 5, name: "sendBytesLong", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "getCLAChannel", descriptor: "()B", is_static: true, static_token: true },
    ApiMethod { token: 6, name: "setIncomingAndReceive", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "setOutgoing", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "setOutgoingAndSend", descriptor: "(SS)V", is_static: false, static_token: false },
    ApiMethod { token: 9, name: "setOutgoingLength", descriptor: "(S)V", is_static: false, static_token: false },
    ApiMethod { token: 10, name: "setOutgoingNoChaining", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 11, name: "getCurrentState", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 12, name: "isCommandChainingCLA", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 13, name: "isSecureMessagingCLA", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 14, name: "isISOInterindustryCLA", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 15, name: "getIncomingLength", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 16, name: "getOffsetCdata", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 17, name: "isValidCLA", descriptor: "()Z", is_static: false, static_token: false },
];

const METHODS_A0000000620101_4: [ApiMethod; 5] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "(S)V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "throwIt", descriptor: "(S)V", is_static: true, static_token: true },
    ApiMethod { token: 1, name: "getReason", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "setReason", descriptor: "(S)V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_11: [ApiMethod; 5] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "(S)V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "throwIt", descriptor: "(S)V", is_static: true, static_token: true },
    ApiMethod { token: 1, name: "getReason", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "setReason", descriptor: "(S)V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_22: [ApiMethod; 6] = [
    ApiMethod { token: 0, name: "assertIntegrity", descriptor: "(Ljava/lang/Object;)V", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "isIntegritySensitive", descriptor: "(Ljava/lang/Object;)Z", is_static: true, static_token: true },
    ApiMethod { token: 2, name: "isIntegritySensitiveArraysSupported", descriptor: "()Z", is_static: true, static_token: true },
    ApiMethod { token: 3, name: "makeIntegritySensitiveArray", descriptor: "(BBS)Ljava/lang/Object;", is_static: true, static_token: true },
    ApiMethod { token: 4, name: "clearArray", descriptor: "(Ljava/lang/Object;)S", is_static: true, static_token: true },
];

const METHODS_A0000000620101_7: [ApiMethod; 5] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "(S)V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "throwIt", descriptor: "(S)V", is_static: true, static_token: true },
    ApiMethod { token: 1, name: "getReason", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "setReason", descriptor: "(S)V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_13: [ApiMethod; 5] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "(S)V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "throwIt", descriptor: "(S)V", is_static: true, static_token: true },
    ApiMethod { token: 1, name: "getReason", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "setReason", descriptor: "(S)V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_14: [ApiMethod; 5] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "(S)V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "throwIt", descriptor: "(S)V", is_static: true, static_token: true },
    ApiMethod { token: 1, name: "getReason", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "setReason", descriptor: "(S)V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_15: [ApiMethod; 6] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "<init>", descriptor: "(S)V", is_static: false, static_token: true },
    ApiMethod { token: 1, name: "getReason", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "throwIt", descriptor: "(S)V", is_static: true, static_token: true },
    ApiMethod { token: 2, name: "setReason", descriptor: "(S)V", is_static: false, static_token: false },
];

const METHODS_A0000000620101_16: [ApiMethod; 9] = [
    ApiMethod { token: 0, name: "arrayCompare", descriptor: "([BS[BSS)B", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "arrayCopy", descriptor: "([BS[BSS)S", is_static: true, static_token: true },
    ApiMethod { token: 2, name: "arrayCopyNonAtomic", descriptor: "([BS[BSS)S", is_static: true, static_token: true },
    ApiMethod { token: 3, name: "arrayFillNonAtomic", descriptor: "([BSSB)S", is_static: true, static_token: true },
    ApiMethod { token: 4, name: "getShort", descriptor: "([BS)S", is_static: true, static_token: true },
    ApiMethod { token: 5, name: "makeShort", descriptor: "(BB)S", is_static: true, static_token: true },
    ApiMethod { token: 6, name: "setShort", descriptor: "([BSS)S", is_static: true, static_token: true },
    ApiMethod { token: 7, name: "arrayFill", descriptor: "([BSSB)S", is_static: true, static_token: true },
];

const CLASSES_A0000000620101: [ApiClass; 23] = [
    ApiClass { token: 0, name: "javacard/framework/ISO7816", is_interface: true, methods: &METHODS_A0000000620101_0 },
    ApiClass { token: 1, name: "javacard/framework/PIN", is_interface: true, methods: &METHODS_A0000000620101_1 },
    ApiClass { token: 2, name: "javacard/framework/Shareable", is_interface: true, methods: &METHODS_A0000000620101_2 },
    ApiClass { token: 3, name: "javacard/framework/Applet", is_interface: false, methods: &METHODS_A0000000620101_3 },
    ApiClass { token: 4, name: "javacard/framework/CardException", is_interface: false, methods: &METHODS_A0000000620101_4 },
    ApiClass { token: 5, name: "javacard/framework/CardRuntimeException", is_interface: false, methods: &METHODS_A0000000620101_5 },
    ApiClass { token: 6, name: "javacard/framework/AID", is_interface: false, methods: &METHODS_A0000000620101_6 },
    ApiClass { token: 7, name: "javacard/framework/ISOException", is_interface: false, methods: &METHODS_A0000000620101_7 },
    ApiClass { token: 8, name: "javacard/framework/JCSystem", is_interface: false, methods: &METHODS_A0000000620101_8 },
    ApiClass { token: 9, name: "javacard/framework/OwnerPIN", is_interface: false, methods: &METHODS_A0000000620101_9 },
    ApiClass { token: 10, name: "javacard/framework/APDU", is_interface: false, methods: &METHODS_A0000000620101_10 },
    ApiClass { token: 11, name: "javacard/framework/PINException", is_interface: false, methods: &METHODS_A0000000620101_11 },
    ApiClass { token: 12, name: "javacard/framework/APDUException", is_interface: false, methods: &METHODS_A0000000620101_12 },
    ApiClass { token: 13, name: "javacard/framework/SystemException", is_interface: false, methods: &METHODS_A0000000620101_13 },
    ApiClass { token: 14, name: "javacard/framework/TransactionException", is_interface: false, methods: &METHODS_A0000000620101_14 },
    ApiClass { token: 15, name: "javacard/framework/UserException", is_interface: false, methods: &METHODS_A0000000620101_15 },
    ApiClass { token: 16, name: "javacard/framework/Util", is_interface: false, methods: &METHODS_A0000000620101_16 },
    ApiClass { token: 17, name: "javacard/framework/MultiSelectable", is_interface: true, methods: &METHODS_A0000000620101_17 },
    ApiClass { token: 18, name: "javacard/framework/AppletEvent", is_interface: true, methods: &METHODS_A0000000620101_18 },
    ApiClass { token: 19, name: "javacard/framework/OwnerPINx", is_interface: true, methods: &METHODS_A0000000620101_19 },
    ApiClass { token: 20, name: "javacard/framework/OwnerPINxWithPredecrement", is_interface: true, methods: &METHODS_A0000000620101_20 },
    ApiClass { token: 21, name: "javacard/framework/OwnerPINBuilder", is_interface: false, methods: &METHODS_A0000000620101_21 },
    ApiClass { token: 22, name: "javacard/framework/SensitiveArrays", is_interface: false, methods: &METHODS_A0000000620101_22 },
];

const METHODS_A0000000620102_0: [ApiMethod; 4] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
];

const METHODS_A0000000620102_4: [ApiMethod; 4] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
];

const METHODS_A0000000620102_27: [ApiMethod; 6] = [
    ApiMethod { token: 0, name: "setP", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "setQ", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "setG", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "getP", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "getQ", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getG", descriptor: "([BS)S", is_static: false, static_token: false },
];

const METHODS_A0000000620102_2: [ApiMethod; 4] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
];

const METHODS_A0000000620102_3: [ApiMethod; 4] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
];

const METHODS_A0000000620102_1: [ApiMethod; 6] = [
    ApiMethod { token: 0, name: "getG", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getP", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getQ", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "setG", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "setP", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "setQ", descriptor: "([BSS)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_5: [ApiMethod; 12] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "getG", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getP", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "getQ", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "setG", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "setP", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 9, name: "setQ", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 10, name: "getX", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 11, name: "setX", descriptor: "([BSS)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_6: [ApiMethod; 12] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "getG", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getP", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "getQ", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "setG", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "setP", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 9, name: "setQ", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 10, name: "getY", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 11, name: "setY", descriptor: "([BSS)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_17: [ApiMethod; 15] = [
    ApiMethod { token: 0, name: "setFieldFP", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "setFieldF2M", descriptor: "(S)V", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "setFieldF2M", descriptor: "(SSS)V", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "setA", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "setB", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "setG", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "setR", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "setK", descriptor: "(S)V", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "getField", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 9, name: "getA", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 10, name: "getB", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 11, name: "getG", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 12, name: "getR", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 13, name: "getK", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 14, name: "copyDomainParametersFrom", descriptor: "(Ljavacard/security/ECKey;)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_18: [ApiMethod; 21] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "setFieldFP", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "setFieldF2M", descriptor: "(S)V", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "setFieldF2M", descriptor: "(SSS)V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "setA", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "setB", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 9, name: "setG", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 10, name: "setR", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 11, name: "setK", descriptor: "(S)V", is_static: false, static_token: false },
    ApiMethod { token: 12, name: "getField", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 13, name: "getA", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 14, name: "getB", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 15, name: "getG", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 16, name: "getR", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 17, name: "getK", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 18, name: "setS", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 19, name: "getS", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 20, name: "copyDomainParametersFrom", descriptor: "(Ljavacard/security/ECKey;)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_19: [ApiMethod; 21] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "setFieldFP", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "setFieldF2M", descriptor: "(S)V", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "setFieldF2M", descriptor: "(SSS)V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "setA", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "setB", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 9, name: "setG", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 10, name: "setR", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 11, name: "setK", descriptor: "(S)V", is_static: false, static_token: false },
    ApiMethod { token: 12, name: "getField", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 13, name: "getA", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 14, name: "getB", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 15, name: "getG", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 16, name: "getR", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 17, name: "getK", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 18, name: "setW", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 19, name: "getW", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 20, name: "copyDomainParametersFrom", descriptor: "(Ljavacard/security/ECKey;)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_23: [ApiMethod; 6] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "setKey", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getKey", descriptor: "([BS)B", is_static: false, static_token: false },
];

const METHODS_A0000000620102_10: [ApiMethod; 6] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "getKey", descriptor: "([BS)B", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "setKey", descriptor: "([BS)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_24: [ApiMethod; 6] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "setKey", descriptor: "([BS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getKey", descriptor: "([BS)B", is_static: false, static_token: false },
];

const METHODS_A0000000620102_28: [ApiMethod; 12] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "setP", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "setQ", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "setG", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "getP", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "getQ", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 9, name: "getG", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 10, name: "setX", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 11, name: "getX", descriptor: "([BS)S", is_static: false, static_token: false },
];

const METHODS_A0000000620102_29: [ApiMethod; 12] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "setP", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "setQ", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "setG", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "getP", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "getQ", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 9, name: "getG", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 10, name: "setY", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 11, name: "getY", descriptor: "([BS)S", is_static: false, static_token: false },
];

const METHODS_A0000000620102_7: [ApiMethod; 14] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "getDP1", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getDQ1", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "getP", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "getPQ", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "getQ", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 9, name: "setDP1", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 10, name: "setDQ1", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 11, name: "setP", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 12, name: "setPQ", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 13, name: "setQ", descriptor: "([BSS)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_8: [ApiMethod; 8] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "getExponent", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getModulus", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "setExponent", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "setModulus", descriptor: "([BSS)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_9: [ApiMethod; 8] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "getExponent", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getModulus", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "setExponent", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "setModulus", descriptor: "([BSS)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_20: [ApiMethod; 6] = [
    ApiMethod { token: 0, name: "clearKey", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getSize", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getType", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isInitialized", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "setKey", descriptor: "([BS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getKey", descriptor: "([BS)B", is_static: false, static_token: false },
];

const METHODS_A0000000620102_25: [ApiMethod; 7] = [
    ApiMethod { token: 0, name: "init", descriptor: "(Ljavacard/security/Key;B)V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "beginVerify", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "sign", descriptor: "([BSS[BS[SS)S", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "verify", descriptor: "([BSS)Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "getLength", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "update", descriptor: "([BSS)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_11: [ApiMethod; 9] = [
    ApiMethod { token: 0, name: "getInstance", descriptor: "(BZ)Ljavacard/security/MessageDigest;", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 1, name: "doFinal", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getInitializedMessageDigestInstance", descriptor: "(BZ)Ljavacard/security/InitializedMessageDigest;", is_static: true, static_token: true },
    ApiMethod { token: 2, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "getLength", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "reset", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "update", descriptor: "([BSS)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_30: [ApiMethod; 8] = [
    ApiMethod { token: 0, name: "open", descriptor: "(B)Ljavacard/security/MessageDigest$OneShot;", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "doFinal", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "getLength", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "reset", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "update", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "close", descriptor: "()V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_26: [ApiMethod; 8] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "doFinal", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "getLength", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "reset", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "update", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "setInitialDigest", descriptor: "([BSS[BSS)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_31: [ApiMethod; 9] = [
    ApiMethod { token: 0, name: "open", descriptor: "(B)Ljavacard/security/InitializedMessageDigest$OneShot;", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "doFinal", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "getLength", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "reset", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "update", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "setInitialDigest", descriptor: "([BSS[BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "close", descriptor: "()V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_12: [ApiMethod; 5] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "(S)V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "throwIt", descriptor: "(S)V", is_static: true, static_token: true },
    ApiMethod { token: 1, name: "getReason", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "setReason", descriptor: "(S)V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_22: [ApiMethod; 6] = [
    ApiMethod { token: 0, name: "getInstance", descriptor: "(BZ)Ljavacard/security/KeyAgreement;", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 1, name: "init", descriptor: "(Ljavacard/security/PrivateKey;)V", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "generateSecret", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
];

const METHODS_A0000000620102_13: [ApiMethod; 4] = [
    ApiMethod { token: 0, name: "buildKey", descriptor: "(BSZ)Ljavacard/security/Key;", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "buildKey", descriptor: "(BBSZ)Ljavacard/security/Key;", is_static: true, static_token: true },
    ApiMethod { token: 2, name: "buildKeyWithSharedDomain", descriptor: "(BBLjavacard/security/Key;Z)Ljavacard/security/Key;", is_static: true, static_token: true },
];

const METHODS_A0000000620102_14: [ApiMethod; 7] = [
    ApiMethod { token: 0, name: "getInstance", descriptor: "(B)Ljavacard/security/RandomData;", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 1, name: "generateData", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "setSeed", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "nextBytes", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
];

const METHODS_A0000000620102_32: [ApiMethod; 7] = [
    ApiMethod { token: 0, name: "open", descriptor: "(B)Ljavacard/security/RandomData$OneShot;", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "generateData", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "setSeed", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "nextBytes", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "close", descriptor: "()V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_16: [ApiMethod; 6] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "(BS)V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "<init>", descriptor: "(Ljavacard/security/PublicKey;Ljavacard/security/PrivateKey;)V", is_static: false, static_token: true },
    ApiMethod { token: 1, name: "genKeyPair", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getPrivate", descriptor: "()Ljavacard/security/PrivateKey;", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "getPublic", descriptor: "()Ljavacard/security/PublicKey;", is_static: false, static_token: false },
];

const METHODS_A0000000620102_15: [ApiMethod; 17] = [
    ApiMethod { token: 0, name: "getInstance", descriptor: "(BZ)Ljavacard/security/Signature;", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 1, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getInstance", descriptor: "(BBBZ)Ljavacard/security/Signature;", is_static: true, static_token: true },
    ApiMethod { token: 2, name: "getLength", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "init", descriptor: "(Ljavacard/security/Key;B)V", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "init", descriptor: "(Ljavacard/security/Key;B[BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "sign", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "update", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "verify", descriptor: "([BSS[BSS)Z", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "setInitialDigest", descriptor: "([BSS[BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 9, name: "signPreComputedHash", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 10, name: "verifyPreComputedHash", descriptor: "([BSS[BSS)Z", is_static: false, static_token: false },
    ApiMethod { token: 11, name: "getMessageDigestAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 12, name: "getCipherAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 13, name: "getPaddingAlgorithm", descriptor: "()B", is_static: false, static_token: false },
];

const METHODS_A0000000620102_33: [ApiMethod; 16] = [
    ApiMethod { token: 0, name: "open", descriptor: "(BBB)Ljavacard/security/Signature$OneShot;", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getLength", descriptor: "()S", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "init", descriptor: "(Ljavacard/security/Key;B)V", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "init", descriptor: "(Ljavacard/security/Key;B[BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "sign", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "update", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "verify", descriptor: "([BSS[BSS)Z", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "setInitialDigest", descriptor: "([BSS[BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 9, name: "signPreComputedHash", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 10, name: "verifyPreComputedHash", descriptor: "([BSS[BSS)Z", is_static: false, static_token: false },
    ApiMethod { token: 11, name: "getMessageDigestAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 12, name: "getCipherAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 13, name: "getPaddingAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 14, name: "close", descriptor: "()V", is_static: false, static_token: false },
];

const METHODS_A0000000620102_21: [ApiMethod; 7] = [
    ApiMethod { token: 0, name: "getInstance", descriptor: "(BZ)Ljavacard/security/Checksum;", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 1, name: "init", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "doFinal", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "update", descriptor: "([BSS)V", is_static: false, static_token: false },
];

const CLASSES_A0000000620102: [ApiClass; 34] = [
    ApiClass { token: 0, name: "javacard/security/Key", is_interface: true, methods: &METHODS_A0000000620102_0 },
    ApiClass { token: 1, name: "javacard/security/DSAKey", is_interface: true, methods: &METHODS_A0000000620102_1 },
    ApiClass { token: 2, name: "javacard/security/PrivateKey", is_interface: true, methods: &METHODS_A0000000620102_2 },
    ApiClass { token: 3, name: "javacard/security/PublicKey", is_interface: true, methods: &METHODS_A0000000620102_3 },
    ApiClass { token: 4, name: "javacard/security/SecretKey", is_interface: true, methods: &METHODS_A0000000620102_4 },
    ApiClass { token: 5, name: "javacard/security/DSAPrivateKey", is_interface: true, methods: &METHODS_A0000000620102_5 },
    ApiClass { token: 6, name: "javacard/security/DSAPublicKey", is_interface: true, methods: &METHODS_A0000000620102_6 },
    ApiClass { token: 7, name: "javacard/security/RSAPrivateCrtKey", is_interface: true, methods: &METHODS_A0000000620102_7 },
    ApiClass { token: 8, name: "javacard/security/RSAPrivateKey", is_interface: true, methods: &METHODS_A0000000620102_8 },
    ApiClass { token: 9, name: "javacard/security/RSAPublicKey", is_interface: true, methods: &METHODS_A0000000620102_9 },
    ApiClass { token: 10, name: "javacard/security/DESKey", is_interface: true, methods: &METHODS_A0000000620102_10 },
    ApiClass { token: 11, name: "javacard/security/MessageDigest", is_interface: false, methods: &METHODS_A0000000620102_11 },
    ApiClass { token: 12, name: "javacard/security/CryptoException", is_interface: false, methods: &METHODS_A0000000620102_12 },
    ApiClass { token: 13, name: "javacard/security/KeyBuilder", is_interface: false, methods: &METHODS_A0000000620102_13 },
    ApiClass { token: 14, name: "javacard/security/RandomData", is_interface: false, methods: &METHODS_A0000000620102_14 },
    ApiClass { token: 15, name: "javacard/security/Signature", is_interface: false, methods: &METHODS_A0000000620102_15 },
    ApiClass { token: 16, name: "javacard/security/KeyPair", is_interface: false, methods: &METHODS_A0000000620102_16 },
    ApiClass { token: 17, name: "javacard/security/ECKey", is_interface: true, methods: &METHODS_A0000000620102_17 },
    ApiClass { token: 18, name: "javacard/security/ECPrivateKey", is_interface: true, methods: &METHODS_A0000000620102_18 },
    ApiClass { token: 19, name: "javacard/security/ECPublicKey", is_interface: true, methods: &METHODS_A0000000620102_19 },
    ApiClass { token: 20, name: "javacard/security/AESKey", is_interface: true, methods: &METHODS_A0000000620102_20 },
    ApiClass { token: 21, name: "javacard/security/Checksum", is_interface: false, methods: &METHODS_A0000000620102_21 },
    ApiClass { token: 22, name: "javacard/security/KeyAgreement", is_interface: false, methods: &METHODS_A0000000620102_22 },
    ApiClass { token: 23, name: "javacard/security/HMACKey", is_interface: true, methods: &METHODS_A0000000620102_23 },
    ApiClass { token: 24, name: "javacard/security/KoreanSEEDKey", is_interface: true, methods: &METHODS_A0000000620102_24 },
    ApiClass { token: 25, name: "javacard/security/SignatureMessageRecovery", is_interface: true, methods: &METHODS_A0000000620102_25 },
    ApiClass { token: 26, name: "javacard/security/InitializedMessageDigest", is_interface: false, methods: &METHODS_A0000000620102_26 },
    ApiClass { token: 27, name: "javacard/security/DHKey", is_interface: true, methods: &METHODS_A0000000620102_27 },
    ApiClass { token: 28, name: "javacard/security/DHPrivateKey", is_interface: true, methods: &METHODS_A0000000620102_28 },
    ApiClass { token: 29, name: "javacard/security/DHPublicKey", is_interface: true, methods: &METHODS_A0000000620102_29 },
    ApiClass { token: 30, name: "javacard/security/MessageDigest$OneShot", is_interface: false, methods: &METHODS_A0000000620102_30 },
    ApiClass { token: 31, name: "javacard/security/InitializedMessageDigest$OneShot", is_interface: false, methods: &METHODS_A0000000620102_31 },
    ApiClass { token: 32, name: "javacard/security/RandomData$OneShot", is_interface: false, methods: &METHODS_A0000000620102_32 },
    ApiClass { token: 33, name: "javacard/security/Signature$OneShot", is_interface: false, methods: &METHODS_A0000000620102_33 },
];

const METHODS_A0000000620201_0: [ApiMethod; 2] = [
    ApiMethod { token: 0, name: "getKeyCipher", descriptor: "()Ljavacardx/crypto/Cipher;", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "setKeyCipher", descriptor: "(Ljavacardx/crypto/Cipher;)V", is_static: false, static_token: false },
];

const METHODS_A0000000620201_1: [ApiMethod; 11] = [
    ApiMethod { token: 0, name: "getInstance", descriptor: "(BZ)Ljavacardx/crypto/Cipher;", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 1, name: "doFinal", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getInstance", descriptor: "(BBZ)Ljavacardx/crypto/Cipher;", is_static: true, static_token: true },
    ApiMethod { token: 2, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "init", descriptor: "(Ljavacard/security/Key;B)V", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "init", descriptor: "(Ljavacard/security/Key;B[BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "update", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "getCipherAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "getPaddingAlgorithm", descriptor: "()B", is_static: false, static_token: false },
];

const METHODS_A0000000620201_2: [ApiMethod; 10] = [
    ApiMethod { token: 0, name: "open", descriptor: "(BB)Ljavacardx/crypto/Cipher$OneShot;", is_static: true, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "doFinal", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "init", descriptor: "(Ljavacard/security/Key;B)V", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "init", descriptor: "(Ljavacard/security/Key;B[BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "update", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "getCipherAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "getPaddingAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "close", descriptor: "()V", is_static: false, static_token: false },
];

const METHODS_A0000000620201_3: [ApiMethod; 13] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "doFinal", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "init", descriptor: "(Ljavacard/security/Key;B)V", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "init", descriptor: "(Ljavacard/security/Key;B[BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "update", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "getCipherAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "getPaddingAlgorithm", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "init", descriptor: "(Ljavacard/security/Key;B[BSSSSS)V", is_static: false, static_token: false },
    ApiMethod { token: 9, name: "updateAAD", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 10, name: "retrieveTag", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 11, name: "verifyTag", descriptor: "([BSSS)Z", is_static: false, static_token: false },
];

const CLASSES_A0000000620201: [ApiClass; 4] = [
    ApiClass { token: 0, name: "javacardx/crypto/KeyEncryption", is_interface: true, methods: &METHODS_A0000000620201_0 },
    ApiClass { token: 1, name: "javacardx/crypto/Cipher", is_interface: false, methods: &METHODS_A0000000620201_1 },
    ApiClass { token: 2, name: "javacardx/crypto/Cipher$OneShot", is_interface: false, methods: &METHODS_A0000000620201_2 },
    ApiClass { token: 3, name: "javacardx/crypto/AEADCipher", is_interface: false, methods: &METHODS_A0000000620201_3 },
];

const METHODS_A0000000620209_0: [ApiMethod; 0] = [
];

const CLASSES_A0000000620209: [ApiClass; 1] = [
    ApiClass { token: 0, name: "javacardx/apdu/ExtendedLength", is_interface: true, methods: &METHODS_A0000000620209_0 },
];

const METHODS_A00000015100_0: [ApiMethod; 1] = [
    ApiMethod { token: 0, name: "processData", descriptor: "([BSS)V", is_static: false, static_token: false },
];

const METHODS_A00000015100_7: [ApiMethod; 4] = [
    ApiMethod { token: 0, name: "init", descriptor: "(B)V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "sign", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "update", descriptor: "([BSS)V", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "recoverKey", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
];

const METHODS_A00000015100_1: [ApiMethod; 11] = [
    ApiMethod { token: 0, name: "isActive", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "isSubmitted", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "isVerified", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "isBlocked", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "getTriesRemaining", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "update", descriptor: "([BSBB)Z", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "resetState", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "blockState", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 8, name: "resetAndUnblockState", descriptor: "()Z", is_static: false, static_token: false },
    ApiMethod { token: 9, name: "setTryLimit", descriptor: "(B)Z", is_static: false, static_token: false },
    ApiMethod { token: 10, name: "verify", descriptor: "([BSBB)S", is_static: false, static_token: false },
];

const METHODS_A00000015100_4: [ApiMethod; 8] = [
    ApiMethod { token: 0, name: "deregisterService", descriptor: "(S)V", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getAID", descriptor: "()Ljavacard/framework/AID;", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "getPrivileges", descriptor: "([BS)S", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "getState", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "isAssociated", descriptor: "(Ljavacard/framework/AID;)Z", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "isPrivileged", descriptor: "(B)Z", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "registerService", descriptor: "(S)V", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "setState", descriptor: "(B)Z", is_static: false, static_token: false },
];

const METHODS_A00000015100_5: [ApiMethod; 1] = [
    ApiMethod { token: 0, name: "getServiceInterface", descriptor: "(Lorg/globalplatform/GPRegistryEntry;S[BSS)Ljavacard/framework/Shareable;", is_static: false, static_token: false },
];

const METHODS_A00000015100_9: [ApiMethod; 1] = [
    ApiMethod { token: 0, name: "requestHTTPAdministrationSession", descriptor: "([BSS)V", is_static: false, static_token: false },
];

const METHODS_A00000015100_10: [ApiMethod; 1] = [
    ApiMethod { token: 0, name: "httpAdministationSessionReport", descriptor: "(S)V", is_static: false, static_token: false },
];

const METHODS_A00000015100_8: [ApiMethod; 1] = [
    ApiMethod { token: 0, name: "processData", descriptor: "([BSS[BS)S", is_static: false, static_token: false },
];

const METHODS_A00000015100_2: [ApiMethod; 7] = [
    ApiMethod { token: 0, name: "processSecurity", descriptor: "(Ljavacard/framework/APDU;)S", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "wrap", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "unwrap", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "decryptData", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "encryptData", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "resetSecurity", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "getSecurityLevel", descriptor: "()B", is_static: false, static_token: false },
];

const METHODS_A00000015100_6: [ApiMethod; 8] = [
    ApiMethod { token: 0, name: "processSecurity", descriptor: "(Ljavacard/framework/APDU;)S", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "wrap", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "unwrap", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "decryptData", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "encryptData", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "resetSecurity", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "getSecurityLevel", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "setSecurityLevel", descriptor: "(B)V", is_static: false, static_token: false },
];

const METHODS_A00000015100_11: [ApiMethod; 8] = [
    ApiMethod { token: 0, name: "processSecurity", descriptor: "(Ljavacard/framework/APDU;)S", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "wrap", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 2, name: "unwrap", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 3, name: "decryptData", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 4, name: "encryptData", descriptor: "([BSS)S", is_static: false, static_token: false },
    ApiMethod { token: 5, name: "resetSecurity", descriptor: "()V", is_static: false, static_token: false },
    ApiMethod { token: 6, name: "getSecurityLevel", descriptor: "()B", is_static: false, static_token: false },
    ApiMethod { token: 7, name: "processSecurity", descriptor: "([BSSS)S", is_static: false, static_token: false },
];

const METHODS_A00000015100_3: [ApiMethod; 12] = [
    ApiMethod { token: 0, name: "<init>", descriptor: "()V", is_static: false, static_token: true },
    ApiMethod { token: 0, name: "equals", descriptor: "(Ljava/lang/Object;)Z", is_static: false, static_token: false },
    ApiMethod { token: 1, name: "getCardContentState", descriptor: "()B", is_static: true, static_token: true },
    ApiMethod { token: 2, name: "getCardState", descriptor: "()B", is_static: true, static_token: true },
    ApiMethod { token: 3, name: "getCVM", descriptor: "(B)Lorg/globalplatform/CVM;", is_static: true, static_token: true },
    ApiMethod { token: 4, name: "getSecureChannel", descriptor: "()Lorg/globalplatform/SecureChannel;", is_static: true, static_token: true },
    ApiMethod { token: 5, name: "lockCard", descriptor: "()Z", is_static: true, static_token: true },
    ApiMethod { token: 6, name: "terminateCard", descriptor: "()Z", is_static: true, static_token: true },
    ApiMethod { token: 7, name: "setATRHistBytes", descriptor: "([BSB)Z", is_static: true, static_token: true },
    ApiMethod { token: 8, name: "setCardContentState", descriptor: "(B)Z", is_static: true, static_token: true },
    ApiMethod { token: 9, name: "getRegistryEntry", descriptor: "(Ljavacard/framework/AID;)Lorg/globalplatform/GPRegistryEntry;", is_static: true, static_token: true },
    ApiMethod { token: 10, name: "getService", descriptor: "(Ljavacard/framework/AID;S)Lorg/globalplatform/GlobalService;", is_static: true, static_token: true },
];

const CLASSES_A00000015100: [ApiClass; 12] = [
    ApiClass { token: 0, name: "org/globalplatform/Application", is_interface: true, methods: &METHODS_A00000015100_0 },
    ApiClass { token: 1, name: "org/globalplatform/CVM", is_interface: true, methods: &METHODS_A00000015100_1 },
    ApiClass { token: 2, name: "org/globalplatform/SecureChannel", is_interface: true, methods: &METHODS_A00000015100_2 },
    ApiClass { token: 3, name: "org/globalplatform/GPSystem", is_interface: false, methods: &METHODS_A00000015100_3 },
    ApiClass { token: 4, name: "org/globalplatform/GPRegistryEntry", is_interface: true, methods: &METHODS_A00000015100_4 },
    ApiClass { token: 5, name: "org/globalplatform/GlobalService", is_interface: true, methods: &METHODS_A00000015100_5 },
    ApiClass { token: 6, name: "org/globalplatform/SecureChannelx", is_interface: true, methods: &METHODS_A00000015100_6 },
    ApiClass { token: 7, name: "org/globalplatform/Authority", is_interface: true, methods: &METHODS_A00000015100_7 },
    ApiClass { token: 8, name: "org/globalplatform/Personalization", is_interface: true, methods: &METHODS_A00000015100_8 },
    ApiClass { token: 9, name: "org/globalplatform/HTTPAdministration", is_interface: true, methods: &METHODS_A00000015100_9 },
    ApiClass { token: 10, name: "org/globalplatform/HTTPReportListener", is_interface: true, methods: &METHODS_A00000015100_10 },
    ApiClass { token: 11, name: "org/globalplatform/SecureChannelx2", is_interface: true, methods: &METHODS_A00000015100_11 },
];

/// Every package this engine knows how to resolve an import against.
pub const PACKAGES: [ApiPackage; 6] = [
    ApiPackage { aid: &[0xa0, 0x00, 0x00, 0x00, 0x62, 0x00, 0x01], name: "java.lang", major: 1, minor: 0, classes: &CLASSES_A0000000620001 },
    ApiPackage { aid: &[0xa0, 0x00, 0x00, 0x00, 0x62, 0x01, 0x01], name: "javacard.framework", major: 1, minor: 6, classes: &CLASSES_A0000000620101 },
    ApiPackage { aid: &[0xa0, 0x00, 0x00, 0x00, 0x62, 0x01, 0x02], name: "javacard.security", major: 1, minor: 6, classes: &CLASSES_A0000000620102 },
    ApiPackage { aid: &[0xa0, 0x00, 0x00, 0x00, 0x62, 0x02, 0x01], name: "javacardx.crypto", major: 1, minor: 6, classes: &CLASSES_A0000000620201 },
    ApiPackage { aid: &[0xa0, 0x00, 0x00, 0x00, 0x62, 0x02, 0x09], name: "javacardx.apdu", major: 1, minor: 0, classes: &CLASSES_A0000000620209 },
    ApiPackage { aid: &[0xa0, 0x00, 0x00, 0x01, 0x51, 0x00], name: "org.globalplatform", major: 1, minor: 5, classes: &CLASSES_A00000015100 },
];
