// Generated by scripts/generate_jcvm_api.py. Do not edit.
// Source: Java Card 3.0.5 export files, read from the development kit. Tokens are what a CAP file uses to name an imported class, field or method.
pub use crate::jcvm_api_ids::{ClassId, MethodId, PackageId};

/// One method an imported package declares, named by its token.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ApiMethod {
    pub token: u8,
    pub id: MethodId,
    pub signature: Signature,
    pub is_static: bool,
    /// Whether the token belongs to the static namespace, which constructors
    /// share with static methods even though they are instance methods.
    pub static_token: bool,
}

/// One class an imported package declares.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ApiClass {
    pub token: u8,
    pub id: ClassId,
    pub is_interface: bool,
    /// Identities of the classes and interfaces this one extends, nearest first. A
    /// catch clause matches any of them, which is how catching a supertype works.
    pub supers: &'static [ClassId],
    pub methods: &'static [ApiMethod],
}

/// One package an applet may import.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ApiPackage {
    pub aid: &'static [u8],
    pub id: PackageId,
    /// The version the export file declares, which an import has to be satisfied by.
    pub major: u8,
    pub minor: u8,
    pub classes: &'static [ApiClass],
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Signature(u8);
impl Signature {
    pub fn empty_parameters(self) -> bool { self.0 & 1 != 0 }
    pub fn init_vector(self) -> bool { self.0 & 2 != 0 }
    pub fn init_mode(self) -> bool { self.0 & 4 != 0 }
    pub fn key_pair_references(self) -> bool { self.0 & 8 != 0 }
    pub fn combined_factory(self) -> bool { self.0 & 16 != 0 }
}

const SUPERS_A0000000620001_0: [ClassId; 0] = [];
const METHODS_A0000000620001_0: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620001_1: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620001_1: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620001_2: [ClassId; 2] = [ClassId::Object, ClassId::Throwable];
const METHODS_A0000000620001_2: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620001_3: [ClassId; 3] = [ClassId::Object, ClassId::Throwable, ClassId::Exception];
const METHODS_A0000000620001_3: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620001_4: [ClassId; 4] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException];
const METHODS_A0000000620001_4: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620001_5: [ClassId; 5] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException, ClassId::IndexOutOfBoundsException];
const METHODS_A0000000620001_5: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620001_6: [ClassId; 4] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException];
const METHODS_A0000000620001_6: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620001_7: [ClassId; 4] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException];
const METHODS_A0000000620001_7: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620001_8: [ClassId; 4] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException];
const METHODS_A0000000620001_8: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620001_9: [ClassId; 4] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException];
const METHODS_A0000000620001_9: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620001_10: [ClassId; 4] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException];
const METHODS_A0000000620001_10: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620001_11: [ClassId; 4] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException];
const METHODS_A0000000620001_11: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
];

const CLASSES_A0000000620001: [ApiClass; 12] = [
    ApiClass { token: 0, id: ClassId::Object, is_interface: false, supers: &SUPERS_A0000000620001_0, methods: &METHODS_A0000000620001_0 },
    ApiClass { token: 1, id: ClassId::Throwable, is_interface: false, supers: &SUPERS_A0000000620001_1, methods: &METHODS_A0000000620001_1 },
    ApiClass { token: 2, id: ClassId::Exception, is_interface: false, supers: &SUPERS_A0000000620001_2, methods: &METHODS_A0000000620001_2 },
    ApiClass { token: 3, id: ClassId::RuntimeException, is_interface: false, supers: &SUPERS_A0000000620001_3, methods: &METHODS_A0000000620001_3 },
    ApiClass { token: 4, id: ClassId::IndexOutOfBoundsException, is_interface: false, supers: &SUPERS_A0000000620001_4, methods: &METHODS_A0000000620001_4 },
    ApiClass { token: 5, id: ClassId::ArrayIndexOutOfBoundsException, is_interface: false, supers: &SUPERS_A0000000620001_5, methods: &METHODS_A0000000620001_5 },
    ApiClass { token: 6, id: ClassId::NegativeArraySizeException, is_interface: false, supers: &SUPERS_A0000000620001_6, methods: &METHODS_A0000000620001_6 },
    ApiClass { token: 7, id: ClassId::NullPointerException, is_interface: false, supers: &SUPERS_A0000000620001_7, methods: &METHODS_A0000000620001_7 },
    ApiClass { token: 8, id: ClassId::ClassCastException, is_interface: false, supers: &SUPERS_A0000000620001_8, methods: &METHODS_A0000000620001_8 },
    ApiClass { token: 9, id: ClassId::ArithmeticException, is_interface: false, supers: &SUPERS_A0000000620001_9, methods: &METHODS_A0000000620001_9 },
    ApiClass { token: 10, id: ClassId::SecurityException, is_interface: false, supers: &SUPERS_A0000000620001_10, methods: &METHODS_A0000000620001_10 },
    ApiClass { token: 11, id: ClassId::ArrayStoreException, is_interface: false, supers: &SUPERS_A0000000620001_11, methods: &METHODS_A0000000620001_11 },
];

const SUPERS_A0000000620101_18: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620101_18: [ApiMethod; 1] = [
    ApiMethod { token: 0, id: MethodId::uninstall, signature: Signature(1), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_0: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620101_0: [ApiMethod; 0] = [
];

const SUPERS_A0000000620101_17: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620101_17: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::select, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::deselect, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_1: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620101_1: [ApiMethod; 4] = [
    ApiMethod { token: 0, id: MethodId::check, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getTriesRemaining, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::isValidated, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::reset, signature: Signature(1), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_19: [ClassId; 2] = [ClassId::Object, ClassId::PIN];
const METHODS_A0000000620101_19: [ApiMethod; 8] = [
    ApiMethod { token: 0, id: MethodId::check, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getTriesRemaining, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::isValidated, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::reset, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::update, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getTryLimit, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::setTryLimit, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::setTriesRemaining, signature: Signature(4), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_20: [ClassId; 3] = [ClassId::Object, ClassId::PIN, ClassId::OwnerPINx];
const METHODS_A0000000620101_20: [ApiMethod; 9] = [
    ApiMethod { token: 0, id: MethodId::check, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getTriesRemaining, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::isValidated, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::reset, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::update, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getTryLimit, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::setTryLimit, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::setTriesRemaining, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::decrementTriesRemaining, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_2: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620101_2: [ApiMethod; 0] = [
];

const SUPERS_A0000000620101_6: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620101_6: [ApiMethod; 7] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(4), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::RIDEquals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::equals, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::getBytes, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::partialEquals, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getPartialBytes, signature: Signature(4), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_5: [ClassId; 4] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException];
const METHODS_A0000000620101_5: [ApiMethod; 5] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(0), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::throwIt, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 1, id: MethodId::getReason, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::setReason, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_8: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620101_8: [ApiMethod; 24] = [
    ApiMethod { token: 0, id: MethodId::abortTransaction, signature: Signature(1), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::beginTransaction, signature: Signature(1), is_static: true, static_token: true },
    ApiMethod { token: 2, id: MethodId::commitTransaction, signature: Signature(1), is_static: true, static_token: true },
    ApiMethod { token: 3, id: MethodId::getAID, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 4, id: MethodId::getAppletShareableInterfaceObject, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 5, id: MethodId::getMaxCommitCapacity, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 6, id: MethodId::getPreviousContextAID, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 7, id: MethodId::getTransactionDepth, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 8, id: MethodId::getUnusedCommitCapacity, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 9, id: MethodId::getVersion, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 10, id: MethodId::isTransient, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 11, id: MethodId::lookupAID, signature: Signature(4), is_static: true, static_token: true },
    ApiMethod { token: 12, id: MethodId::makeTransientBooleanArray, signature: Signature(4), is_static: true, static_token: true },
    ApiMethod { token: 13, id: MethodId::makeTransientByteArray, signature: Signature(4), is_static: true, static_token: true },
    ApiMethod { token: 14, id: MethodId::makeTransientObjectArray, signature: Signature(4), is_static: true, static_token: true },
    ApiMethod { token: 15, id: MethodId::makeTransientShortArray, signature: Signature(4), is_static: true, static_token: true },
    ApiMethod { token: 16, id: MethodId::getAvailableMemory, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 17, id: MethodId::isObjectDeletionSupported, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 18, id: MethodId::requestObjectDeletion, signature: Signature(1), is_static: true, static_token: true },
    ApiMethod { token: 19, id: MethodId::getAssignedChannel, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 20, id: MethodId::isAppletActive, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 21, id: MethodId::makeGlobalArray, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 22, id: MethodId::getAvailableMemory, signature: Signature(4), is_static: true, static_token: true },
];

const SUPERS_A0000000620101_12: [ClassId; 5] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException, ClassId::CardRuntimeException];
const METHODS_A0000000620101_12: [ApiMethod; 5] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(0), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::throwIt, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 1, id: MethodId::getReason, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::setReason, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_9: [ClassId; 2] = [ClassId::Object, ClassId::PIN];
const METHODS_A0000000620101_9: [ApiMethod; 10] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(4), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::check, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getTriesRemaining, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::getValidatedFlag, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::isValidated, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::reset, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::resetAndUnblock, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::setValidatedFlag, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::update, signature: Signature(4), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_21: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620101_21: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::buildOwnerPIN, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_3: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620101_3: [ApiMethod; 11] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::install, signature: Signature(4), is_static: true, static_token: true },
    ApiMethod { token: 1, id: MethodId::register, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::reSelectingApplet, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 2, id: MethodId::register, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::selectingApplet, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::deselect, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getShareableInterfaceObject, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::select, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::process, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_10: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620101_10: [ApiMethod; 25] = [
    ApiMethod { token: 0, id: MethodId::getInBlockSize, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getOutBlockSize, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 1, id: MethodId::getBuffer, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getProtocol, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 2, id: MethodId::getNAD, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::waitExtension, signature: Signature(1), is_static: true, static_token: true },
    ApiMethod { token: 3, id: MethodId::receiveBytes, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::getCurrentAPDU, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 4, id: MethodId::sendBytes, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getCurrentAPDUBuffer, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 5, id: MethodId::sendBytesLong, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::getCLAChannel, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 6, id: MethodId::setIncomingAndReceive, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::setOutgoing, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::setOutgoingAndSend, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 9, id: MethodId::setOutgoingLength, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 10, id: MethodId::setOutgoingNoChaining, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 11, id: MethodId::getCurrentState, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 12, id: MethodId::isCommandChainingCLA, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 13, id: MethodId::isSecureMessagingCLA, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 14, id: MethodId::isISOInterindustryCLA, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 15, id: MethodId::getIncomingLength, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 16, id: MethodId::getOffsetCdata, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 17, id: MethodId::isValidCLA, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_4: [ClassId; 3] = [ClassId::Object, ClassId::Throwable, ClassId::Exception];
const METHODS_A0000000620101_4: [ApiMethod; 5] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(0), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::throwIt, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 1, id: MethodId::getReason, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::setReason, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_11: [ClassId; 5] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException, ClassId::CardRuntimeException];
const METHODS_A0000000620101_11: [ApiMethod; 5] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(0), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::throwIt, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 1, id: MethodId::getReason, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::setReason, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_22: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620101_22: [ApiMethod; 6] = [
    ApiMethod { token: 0, id: MethodId::assertIntegrity, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::isIntegritySensitive, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 2, id: MethodId::isIntegritySensitiveArraysSupported, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 3, id: MethodId::makeIntegritySensitiveArray, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 4, id: MethodId::clearArray, signature: Signature(0), is_static: true, static_token: true },
];

const SUPERS_A0000000620101_7: [ClassId; 5] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException, ClassId::CardRuntimeException];
const METHODS_A0000000620101_7: [ApiMethod; 5] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(0), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::throwIt, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 1, id: MethodId::getReason, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::setReason, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_13: [ClassId; 5] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException, ClassId::CardRuntimeException];
const METHODS_A0000000620101_13: [ApiMethod; 5] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(0), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::throwIt, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 1, id: MethodId::getReason, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::setReason, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_14: [ClassId; 5] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException, ClassId::CardRuntimeException];
const METHODS_A0000000620101_14: [ApiMethod; 5] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(0), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::throwIt, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 1, id: MethodId::getReason, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::setReason, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_15: [ClassId; 4] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::CardException];
const METHODS_A0000000620101_15: [ApiMethod; 6] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::Constructor, signature: Signature(0), is_static: false, static_token: true },
    ApiMethod { token: 1, id: MethodId::getReason, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::throwIt, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 2, id: MethodId::setReason, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620101_16: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620101_16: [ApiMethod; 9] = [
    ApiMethod { token: 0, id: MethodId::arrayCompare, signature: Signature(2), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::arrayCopy, signature: Signature(2), is_static: true, static_token: true },
    ApiMethod { token: 2, id: MethodId::arrayCopyNonAtomic, signature: Signature(2), is_static: true, static_token: true },
    ApiMethod { token: 3, id: MethodId::arrayFillNonAtomic, signature: Signature(6), is_static: true, static_token: true },
    ApiMethod { token: 4, id: MethodId::getShort, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 5, id: MethodId::makeShort, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 6, id: MethodId::setShort, signature: Signature(2), is_static: true, static_token: true },
    ApiMethod { token: 7, id: MethodId::arrayFill, signature: Signature(6), is_static: true, static_token: true },
];

const CLASSES_A0000000620101: [ApiClass; 23] = [
    ApiClass { token: 0, id: ClassId::ISO7816, is_interface: true, supers: &SUPERS_A0000000620101_0, methods: &METHODS_A0000000620101_0 },
    ApiClass { token: 1, id: ClassId::PIN, is_interface: true, supers: &SUPERS_A0000000620101_1, methods: &METHODS_A0000000620101_1 },
    ApiClass { token: 2, id: ClassId::Shareable, is_interface: true, supers: &SUPERS_A0000000620101_2, methods: &METHODS_A0000000620101_2 },
    ApiClass { token: 3, id: ClassId::Applet, is_interface: false, supers: &SUPERS_A0000000620101_3, methods: &METHODS_A0000000620101_3 },
    ApiClass { token: 4, id: ClassId::CardException, is_interface: false, supers: &SUPERS_A0000000620101_4, methods: &METHODS_A0000000620101_4 },
    ApiClass { token: 5, id: ClassId::CardRuntimeException, is_interface: false, supers: &SUPERS_A0000000620101_5, methods: &METHODS_A0000000620101_5 },
    ApiClass { token: 6, id: ClassId::AID, is_interface: false, supers: &SUPERS_A0000000620101_6, methods: &METHODS_A0000000620101_6 },
    ApiClass { token: 7, id: ClassId::ISOException, is_interface: false, supers: &SUPERS_A0000000620101_7, methods: &METHODS_A0000000620101_7 },
    ApiClass { token: 8, id: ClassId::JCSystem, is_interface: false, supers: &SUPERS_A0000000620101_8, methods: &METHODS_A0000000620101_8 },
    ApiClass { token: 9, id: ClassId::OwnerPIN, is_interface: false, supers: &SUPERS_A0000000620101_9, methods: &METHODS_A0000000620101_9 },
    ApiClass { token: 10, id: ClassId::APDU, is_interface: false, supers: &SUPERS_A0000000620101_10, methods: &METHODS_A0000000620101_10 },
    ApiClass { token: 11, id: ClassId::PINException, is_interface: false, supers: &SUPERS_A0000000620101_11, methods: &METHODS_A0000000620101_11 },
    ApiClass { token: 12, id: ClassId::APDUException, is_interface: false, supers: &SUPERS_A0000000620101_12, methods: &METHODS_A0000000620101_12 },
    ApiClass { token: 13, id: ClassId::SystemException, is_interface: false, supers: &SUPERS_A0000000620101_13, methods: &METHODS_A0000000620101_13 },
    ApiClass { token: 14, id: ClassId::TransactionException, is_interface: false, supers: &SUPERS_A0000000620101_14, methods: &METHODS_A0000000620101_14 },
    ApiClass { token: 15, id: ClassId::UserException, is_interface: false, supers: &SUPERS_A0000000620101_15, methods: &METHODS_A0000000620101_15 },
    ApiClass { token: 16, id: ClassId::Util, is_interface: false, supers: &SUPERS_A0000000620101_16, methods: &METHODS_A0000000620101_16 },
    ApiClass { token: 17, id: ClassId::MultiSelectable, is_interface: true, supers: &SUPERS_A0000000620101_17, methods: &METHODS_A0000000620101_17 },
    ApiClass { token: 18, id: ClassId::AppletEvent, is_interface: true, supers: &SUPERS_A0000000620101_18, methods: &METHODS_A0000000620101_18 },
    ApiClass { token: 19, id: ClassId::OwnerPINx, is_interface: true, supers: &SUPERS_A0000000620101_19, methods: &METHODS_A0000000620101_19 },
    ApiClass { token: 20, id: ClassId::OwnerPINxWithPredecrement, is_interface: true, supers: &SUPERS_A0000000620101_20, methods: &METHODS_A0000000620101_20 },
    ApiClass { token: 21, id: ClassId::OwnerPINBuilder, is_interface: false, supers: &SUPERS_A0000000620101_21, methods: &METHODS_A0000000620101_21 },
    ApiClass { token: 22, id: ClassId::SensitiveArrays, is_interface: false, supers: &SUPERS_A0000000620101_22, methods: &METHODS_A0000000620101_22 },
];

const SUPERS_A0000000620102_0: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620102_0: [ApiMethod; 4] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_4: [ClassId; 2] = [ClassId::Object, ClassId::Key];
const METHODS_A0000000620102_4: [ApiMethod; 4] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_27: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620102_27: [ApiMethod; 6] = [
    ApiMethod { token: 0, id: MethodId::setP, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::setQ, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::setG, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::getP, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::getQ, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getG, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_2: [ClassId; 2] = [ClassId::Object, ClassId::Key];
const METHODS_A0000000620102_2: [ApiMethod; 4] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_3: [ClassId; 2] = [ClassId::Object, ClassId::Key];
const METHODS_A0000000620102_3: [ApiMethod; 4] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_1: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620102_1: [ApiMethod; 6] = [
    ApiMethod { token: 0, id: MethodId::getG, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getP, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getQ, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::setG, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::setP, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::setQ, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_5: [ClassId; 4] = [ClassId::Object, ClassId::Key, ClassId::PrivateKey, ClassId::DSAKey];
const METHODS_A0000000620102_5: [ApiMethod; 12] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::getG, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getP, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::getQ, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::setG, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::setP, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 9, id: MethodId::setQ, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 10, id: MethodId::getX, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 11, id: MethodId::setX, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_6: [ClassId; 4] = [ClassId::Object, ClassId::Key, ClassId::PublicKey, ClassId::DSAKey];
const METHODS_A0000000620102_6: [ApiMethod; 12] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::getG, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getP, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::getQ, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::setG, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::setP, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 9, id: MethodId::setQ, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 10, id: MethodId::getY, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 11, id: MethodId::setY, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_17: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620102_17: [ApiMethod; 15] = [
    ApiMethod { token: 0, id: MethodId::setFieldFP, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::setFieldF2M, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::setFieldF2M, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::setA, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::setB, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::setG, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::setR, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::setK, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::getField, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 9, id: MethodId::getA, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 10, id: MethodId::getB, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 11, id: MethodId::getG, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 12, id: MethodId::getR, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 13, id: MethodId::getK, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 14, id: MethodId::copyDomainParametersFrom, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_18: [ClassId; 4] = [ClassId::Object, ClassId::Key, ClassId::PrivateKey, ClassId::ECKey];
const METHODS_A0000000620102_18: [ApiMethod; 21] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::setFieldFP, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::setFieldF2M, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::setFieldF2M, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::setA, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::setB, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 9, id: MethodId::setG, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 10, id: MethodId::setR, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 11, id: MethodId::setK, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 12, id: MethodId::getField, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 13, id: MethodId::getA, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 14, id: MethodId::getB, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 15, id: MethodId::getG, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 16, id: MethodId::getR, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 17, id: MethodId::getK, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 18, id: MethodId::setS, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 19, id: MethodId::getS, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 20, id: MethodId::copyDomainParametersFrom, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_19: [ClassId; 4] = [ClassId::Object, ClassId::Key, ClassId::PublicKey, ClassId::ECKey];
const METHODS_A0000000620102_19: [ApiMethod; 21] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::setFieldFP, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::setFieldF2M, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::setFieldF2M, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::setA, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::setB, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 9, id: MethodId::setG, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 10, id: MethodId::setR, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 11, id: MethodId::setK, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 12, id: MethodId::getField, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 13, id: MethodId::getA, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 14, id: MethodId::getB, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 15, id: MethodId::getG, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 16, id: MethodId::getR, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 17, id: MethodId::getK, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 18, id: MethodId::setW, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 19, id: MethodId::getW, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 20, id: MethodId::copyDomainParametersFrom, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_23: [ClassId; 3] = [ClassId::Object, ClassId::Key, ClassId::SecretKey];
const METHODS_A0000000620102_23: [ApiMethod; 6] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::setKey, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getKey, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_10: [ClassId; 3] = [ClassId::Object, ClassId::Key, ClassId::SecretKey];
const METHODS_A0000000620102_10: [ApiMethod; 6] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::getKey, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::setKey, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_24: [ClassId; 3] = [ClassId::Object, ClassId::Key, ClassId::SecretKey];
const METHODS_A0000000620102_24: [ApiMethod; 6] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::setKey, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getKey, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_28: [ClassId; 4] = [ClassId::Object, ClassId::Key, ClassId::PrivateKey, ClassId::DHKey];
const METHODS_A0000000620102_28: [ApiMethod; 12] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::setP, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::setQ, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::setG, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::getP, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::getQ, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 9, id: MethodId::getG, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 10, id: MethodId::setX, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 11, id: MethodId::getX, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_29: [ClassId; 4] = [ClassId::Object, ClassId::Key, ClassId::PublicKey, ClassId::DHKey];
const METHODS_A0000000620102_29: [ApiMethod; 12] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::setP, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::setQ, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::setG, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::getP, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::getQ, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 9, id: MethodId::getG, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 10, id: MethodId::setY, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 11, id: MethodId::getY, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_7: [ClassId; 3] = [ClassId::Object, ClassId::Key, ClassId::PrivateKey];
const METHODS_A0000000620102_7: [ApiMethod; 14] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::getDP1, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getDQ1, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::getP, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::getPQ, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::getQ, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 9, id: MethodId::setDP1, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 10, id: MethodId::setDQ1, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 11, id: MethodId::setP, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 12, id: MethodId::setPQ, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 13, id: MethodId::setQ, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_8: [ClassId; 3] = [ClassId::Object, ClassId::Key, ClassId::PrivateKey];
const METHODS_A0000000620102_8: [ApiMethod; 8] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::getExponent, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getModulus, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::setExponent, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::setModulus, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_9: [ClassId; 3] = [ClassId::Object, ClassId::Key, ClassId::PublicKey];
const METHODS_A0000000620102_9: [ApiMethod; 8] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::getExponent, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getModulus, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::setExponent, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::setModulus, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_20: [ClassId; 3] = [ClassId::Object, ClassId::Key, ClassId::SecretKey];
const METHODS_A0000000620102_20: [ApiMethod; 6] = [
    ApiMethod { token: 0, id: MethodId::clearKey, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getSize, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getType, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isInitialized, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::setKey, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getKey, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_25: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620102_25: [ApiMethod; 7] = [
    ApiMethod { token: 0, id: MethodId::init, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::beginVerify, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::sign, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::verify, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::getLength, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::update, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_11: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620102_11: [ApiMethod; 9] = [
    ApiMethod { token: 0, id: MethodId::getInstance, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 1, id: MethodId::doFinal, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getInitializedMessageDigestInstance, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 2, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::getLength, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::reset, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::update, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_30: [ClassId; 2] = [ClassId::Object, ClassId::MessageDigest];
const METHODS_A0000000620102_30: [ApiMethod; 8] = [
    ApiMethod { token: 0, id: MethodId::open, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::doFinal, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::getLength, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::reset, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::update, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::close, signature: Signature(1), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_26: [ClassId; 2] = [ClassId::Object, ClassId::MessageDigest];
const METHODS_A0000000620102_26: [ApiMethod; 8] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::doFinal, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::getLength, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::reset, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::update, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::setInitialDigest, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_31: [ClassId; 3] = [ClassId::Object, ClassId::MessageDigest, ClassId::InitializedMessageDigest];
const METHODS_A0000000620102_31: [ApiMethod; 9] = [
    ApiMethod { token: 0, id: MethodId::open, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::doFinal, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::getLength, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::reset, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::update, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::setInitialDigest, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::close, signature: Signature(1), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_12: [ClassId; 5] = [ClassId::Object, ClassId::Throwable, ClassId::Exception, ClassId::RuntimeException, ClassId::CardRuntimeException];
const METHODS_A0000000620102_12: [ApiMethod; 5] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(0), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::throwIt, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 1, id: MethodId::getReason, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::setReason, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_22: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620102_22: [ApiMethod; 6] = [
    ApiMethod { token: 0, id: MethodId::getInstance, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 1, id: MethodId::init, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::generateSecret, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_13: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620102_13: [ApiMethod; 4] = [
    ApiMethod { token: 0, id: MethodId::buildKey, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::buildKey, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 2, id: MethodId::buildKeyWithSharedDomain, signature: Signature(0), is_static: true, static_token: true },
];

const SUPERS_A0000000620102_14: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620102_14: [ApiMethod; 7] = [
    ApiMethod { token: 0, id: MethodId::getInstance, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 1, id: MethodId::generateData, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::setSeed, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::nextBytes, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_32: [ClassId; 2] = [ClassId::Object, ClassId::RandomData];
const METHODS_A0000000620102_32: [ApiMethod; 7] = [
    ApiMethod { token: 0, id: MethodId::open, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::generateData, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::setSeed, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::nextBytes, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::close, signature: Signature(1), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_16: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620102_16: [ApiMethod; 6] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(0), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::Constructor, signature: Signature(8), is_static: false, static_token: true },
    ApiMethod { token: 1, id: MethodId::genKeyPair, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getPrivate, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::getPublic, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_15: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620102_15: [ApiMethod; 17] = [
    ApiMethod { token: 0, id: MethodId::getInstance, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 1, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getInstance, signature: Signature(16), is_static: true, static_token: true },
    ApiMethod { token: 2, id: MethodId::getLength, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::init, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::init, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::sign, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::update, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::verify, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::setInitialDigest, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 9, id: MethodId::signPreComputedHash, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 10, id: MethodId::verifyPreComputedHash, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 11, id: MethodId::getMessageDigestAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 12, id: MethodId::getCipherAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 13, id: MethodId::getPaddingAlgorithm, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_33: [ClassId; 2] = [ClassId::Object, ClassId::Signature];
const METHODS_A0000000620102_33: [ApiMethod; 16] = [
    ApiMethod { token: 0, id: MethodId::open, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getLength, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::init, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::init, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::sign, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::update, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::verify, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::setInitialDigest, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 9, id: MethodId::signPreComputedHash, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 10, id: MethodId::verifyPreComputedHash, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 11, id: MethodId::getMessageDigestAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 12, id: MethodId::getCipherAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 13, id: MethodId::getPaddingAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 14, id: MethodId::close, signature: Signature(1), is_static: false, static_token: false },
];

const SUPERS_A0000000620102_21: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620102_21: [ApiMethod; 7] = [
    ApiMethod { token: 0, id: MethodId::getInstance, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 1, id: MethodId::init, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::doFinal, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::update, signature: Signature(2), is_static: false, static_token: false },
];

const CLASSES_A0000000620102: [ApiClass; 34] = [
    ApiClass { token: 0, id: ClassId::Key, is_interface: true, supers: &SUPERS_A0000000620102_0, methods: &METHODS_A0000000620102_0 },
    ApiClass { token: 1, id: ClassId::DSAKey, is_interface: true, supers: &SUPERS_A0000000620102_1, methods: &METHODS_A0000000620102_1 },
    ApiClass { token: 2, id: ClassId::PrivateKey, is_interface: true, supers: &SUPERS_A0000000620102_2, methods: &METHODS_A0000000620102_2 },
    ApiClass { token: 3, id: ClassId::PublicKey, is_interface: true, supers: &SUPERS_A0000000620102_3, methods: &METHODS_A0000000620102_3 },
    ApiClass { token: 4, id: ClassId::SecretKey, is_interface: true, supers: &SUPERS_A0000000620102_4, methods: &METHODS_A0000000620102_4 },
    ApiClass { token: 5, id: ClassId::DSAPrivateKey, is_interface: true, supers: &SUPERS_A0000000620102_5, methods: &METHODS_A0000000620102_5 },
    ApiClass { token: 6, id: ClassId::DSAPublicKey, is_interface: true, supers: &SUPERS_A0000000620102_6, methods: &METHODS_A0000000620102_6 },
    ApiClass { token: 7, id: ClassId::RSAPrivateCrtKey, is_interface: true, supers: &SUPERS_A0000000620102_7, methods: &METHODS_A0000000620102_7 },
    ApiClass { token: 8, id: ClassId::RSAPrivateKey, is_interface: true, supers: &SUPERS_A0000000620102_8, methods: &METHODS_A0000000620102_8 },
    ApiClass { token: 9, id: ClassId::RSAPublicKey, is_interface: true, supers: &SUPERS_A0000000620102_9, methods: &METHODS_A0000000620102_9 },
    ApiClass { token: 10, id: ClassId::DESKey, is_interface: true, supers: &SUPERS_A0000000620102_10, methods: &METHODS_A0000000620102_10 },
    ApiClass { token: 11, id: ClassId::MessageDigest, is_interface: false, supers: &SUPERS_A0000000620102_11, methods: &METHODS_A0000000620102_11 },
    ApiClass { token: 12, id: ClassId::CryptoException, is_interface: false, supers: &SUPERS_A0000000620102_12, methods: &METHODS_A0000000620102_12 },
    ApiClass { token: 13, id: ClassId::KeyBuilder, is_interface: false, supers: &SUPERS_A0000000620102_13, methods: &METHODS_A0000000620102_13 },
    ApiClass { token: 14, id: ClassId::RandomData, is_interface: false, supers: &SUPERS_A0000000620102_14, methods: &METHODS_A0000000620102_14 },
    ApiClass { token: 15, id: ClassId::Signature, is_interface: false, supers: &SUPERS_A0000000620102_15, methods: &METHODS_A0000000620102_15 },
    ApiClass { token: 16, id: ClassId::KeyPair, is_interface: false, supers: &SUPERS_A0000000620102_16, methods: &METHODS_A0000000620102_16 },
    ApiClass { token: 17, id: ClassId::ECKey, is_interface: true, supers: &SUPERS_A0000000620102_17, methods: &METHODS_A0000000620102_17 },
    ApiClass { token: 18, id: ClassId::ECPrivateKey, is_interface: true, supers: &SUPERS_A0000000620102_18, methods: &METHODS_A0000000620102_18 },
    ApiClass { token: 19, id: ClassId::ECPublicKey, is_interface: true, supers: &SUPERS_A0000000620102_19, methods: &METHODS_A0000000620102_19 },
    ApiClass { token: 20, id: ClassId::AESKey, is_interface: true, supers: &SUPERS_A0000000620102_20, methods: &METHODS_A0000000620102_20 },
    ApiClass { token: 21, id: ClassId::Checksum, is_interface: false, supers: &SUPERS_A0000000620102_21, methods: &METHODS_A0000000620102_21 },
    ApiClass { token: 22, id: ClassId::KeyAgreement, is_interface: false, supers: &SUPERS_A0000000620102_22, methods: &METHODS_A0000000620102_22 },
    ApiClass { token: 23, id: ClassId::HMACKey, is_interface: true, supers: &SUPERS_A0000000620102_23, methods: &METHODS_A0000000620102_23 },
    ApiClass { token: 24, id: ClassId::KoreanSEEDKey, is_interface: true, supers: &SUPERS_A0000000620102_24, methods: &METHODS_A0000000620102_24 },
    ApiClass { token: 25, id: ClassId::SignatureMessageRecovery, is_interface: true, supers: &SUPERS_A0000000620102_25, methods: &METHODS_A0000000620102_25 },
    ApiClass { token: 26, id: ClassId::InitializedMessageDigest, is_interface: false, supers: &SUPERS_A0000000620102_26, methods: &METHODS_A0000000620102_26 },
    ApiClass { token: 27, id: ClassId::DHKey, is_interface: true, supers: &SUPERS_A0000000620102_27, methods: &METHODS_A0000000620102_27 },
    ApiClass { token: 28, id: ClassId::DHPrivateKey, is_interface: true, supers: &SUPERS_A0000000620102_28, methods: &METHODS_A0000000620102_28 },
    ApiClass { token: 29, id: ClassId::DHPublicKey, is_interface: true, supers: &SUPERS_A0000000620102_29, methods: &METHODS_A0000000620102_29 },
    ApiClass { token: 30, id: ClassId::MessageDigest_OneShot, is_interface: false, supers: &SUPERS_A0000000620102_30, methods: &METHODS_A0000000620102_30 },
    ApiClass { token: 31, id: ClassId::InitializedMessageDigest_OneShot, is_interface: false, supers: &SUPERS_A0000000620102_31, methods: &METHODS_A0000000620102_31 },
    ApiClass { token: 32, id: ClassId::RandomData_OneShot, is_interface: false, supers: &SUPERS_A0000000620102_32, methods: &METHODS_A0000000620102_32 },
    ApiClass { token: 33, id: ClassId::Signature_OneShot, is_interface: false, supers: &SUPERS_A0000000620102_33, methods: &METHODS_A0000000620102_33 },
];

const SUPERS_A0000000620201_0: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620201_0: [ApiMethod; 2] = [
    ApiMethod { token: 0, id: MethodId::getKeyCipher, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::setKeyCipher, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620201_1: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620201_1: [ApiMethod; 11] = [
    ApiMethod { token: 0, id: MethodId::getInstance, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 1, id: MethodId::doFinal, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getInstance, signature: Signature(16), is_static: true, static_token: true },
    ApiMethod { token: 2, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::init, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::init, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::update, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::getCipherAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::getPaddingAlgorithm, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A0000000620201_2: [ClassId; 2] = [ClassId::Object, ClassId::Cipher];
const METHODS_A0000000620201_2: [ApiMethod; 10] = [
    ApiMethod { token: 0, id: MethodId::open, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::doFinal, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::init, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::init, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::update, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::getCipherAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::getPaddingAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::close, signature: Signature(1), is_static: false, static_token: false },
];

const SUPERS_A0000000620201_3: [ClassId; 2] = [ClassId::Object, ClassId::Cipher];
const METHODS_A0000000620201_3: [ApiMethod; 13] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::doFinal, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::init, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::init, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::update, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::getCipherAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::getPaddingAlgorithm, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::init, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 9, id: MethodId::updateAAD, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 10, id: MethodId::retrieveTag, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 11, id: MethodId::verifyTag, signature: Signature(2), is_static: false, static_token: false },
];

const CLASSES_A0000000620201: [ApiClass; 4] = [
    ApiClass { token: 0, id: ClassId::KeyEncryption, is_interface: true, supers: &SUPERS_A0000000620201_0, methods: &METHODS_A0000000620201_0 },
    ApiClass { token: 1, id: ClassId::Cipher, is_interface: false, supers: &SUPERS_A0000000620201_1, methods: &METHODS_A0000000620201_1 },
    ApiClass { token: 2, id: ClassId::Cipher_OneShot, is_interface: false, supers: &SUPERS_A0000000620201_2, methods: &METHODS_A0000000620201_2 },
    ApiClass { token: 3, id: ClassId::AEADCipher, is_interface: false, supers: &SUPERS_A0000000620201_3, methods: &METHODS_A0000000620201_3 },
];

const SUPERS_A0000000620209_0: [ClassId; 1] = [ClassId::Object];
const METHODS_A0000000620209_0: [ApiMethod; 0] = [
];

const CLASSES_A0000000620209: [ApiClass; 1] = [
    ApiClass { token: 0, id: ClassId::ExtendedLength, is_interface: true, supers: &SUPERS_A0000000620209_0, methods: &METHODS_A0000000620209_0 },
];

const SUPERS_A00000015100_0: [ClassId; 2] = [ClassId::Object, ClassId::Shareable];
const METHODS_A00000015100_0: [ApiMethod; 1] = [
    ApiMethod { token: 0, id: MethodId::processData, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A00000015100_7: [ClassId; 2] = [ClassId::Object, ClassId::Shareable];
const METHODS_A00000015100_7: [ApiMethod; 4] = [
    ApiMethod { token: 0, id: MethodId::init, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::sign, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::update, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::recoverKey, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A00000015100_1: [ClassId; 2] = [ClassId::Object, ClassId::Shareable];
const METHODS_A00000015100_1: [ApiMethod; 11] = [
    ApiMethod { token: 0, id: MethodId::isActive, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::isSubmitted, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::isVerified, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::isBlocked, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::getTriesRemaining, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::update, signature: Signature(4), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::resetState, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::blockState, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 8, id: MethodId::resetAndUnblockState, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 9, id: MethodId::setTryLimit, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 10, id: MethodId::verify, signature: Signature(4), is_static: false, static_token: false },
];

const SUPERS_A00000015100_4: [ClassId; 2] = [ClassId::Object, ClassId::Shareable];
const METHODS_A00000015100_4: [ApiMethod; 8] = [
    ApiMethod { token: 0, id: MethodId::deregisterService, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getAID, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::getPrivileges, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::getState, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::isAssociated, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::isPrivileged, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::registerService, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::setState, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A00000015100_5: [ClassId; 2] = [ClassId::Object, ClassId::Shareable];
const METHODS_A00000015100_5: [ApiMethod; 1] = [
    ApiMethod { token: 0, id: MethodId::getServiceInterface, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A00000015100_9: [ClassId; 2] = [ClassId::Object, ClassId::Shareable];
const METHODS_A00000015100_9: [ApiMethod; 1] = [
    ApiMethod { token: 0, id: MethodId::requestHTTPAdministrationSession, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A00000015100_10: [ClassId; 2] = [ClassId::Object, ClassId::Shareable];
const METHODS_A00000015100_10: [ApiMethod; 1] = [
    ApiMethod { token: 0, id: MethodId::httpAdministationSessionReport, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A00000015100_8: [ClassId; 2] = [ClassId::Object, ClassId::Shareable];
const METHODS_A00000015100_8: [ApiMethod; 1] = [
    ApiMethod { token: 0, id: MethodId::processData, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A00000015100_2: [ClassId; 2] = [ClassId::Object, ClassId::Shareable];
const METHODS_A00000015100_2: [ApiMethod; 7] = [
    ApiMethod { token: 0, id: MethodId::processSecurity, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::wrap, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::unwrap, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::decryptData, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::encryptData, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::resetSecurity, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::getSecurityLevel, signature: Signature(0), is_static: false, static_token: false },
];

const SUPERS_A00000015100_6: [ClassId; 3] = [ClassId::Object, ClassId::Shareable, ClassId::SecureChannel];
const METHODS_A00000015100_6: [ApiMethod; 8] = [
    ApiMethod { token: 0, id: MethodId::processSecurity, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::wrap, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::unwrap, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::decryptData, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::encryptData, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::resetSecurity, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::getSecurityLevel, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::setSecurityLevel, signature: Signature(4), is_static: false, static_token: false },
];

const SUPERS_A00000015100_11: [ClassId; 3] = [ClassId::Object, ClassId::Shareable, ClassId::SecureChannel];
const METHODS_A00000015100_11: [ApiMethod; 8] = [
    ApiMethod { token: 0, id: MethodId::processSecurity, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::wrap, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 2, id: MethodId::unwrap, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 3, id: MethodId::decryptData, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 4, id: MethodId::encryptData, signature: Signature(2), is_static: false, static_token: false },
    ApiMethod { token: 5, id: MethodId::resetSecurity, signature: Signature(1), is_static: false, static_token: false },
    ApiMethod { token: 6, id: MethodId::getSecurityLevel, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 7, id: MethodId::processSecurity, signature: Signature(2), is_static: false, static_token: false },
];

const SUPERS_A00000015100_3: [ClassId; 1] = [ClassId::Object];
const METHODS_A00000015100_3: [ApiMethod; 12] = [
    ApiMethod { token: 0, id: MethodId::Constructor, signature: Signature(1), is_static: false, static_token: true },
    ApiMethod { token: 0, id: MethodId::equals, signature: Signature(0), is_static: false, static_token: false },
    ApiMethod { token: 1, id: MethodId::getCardContentState, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 2, id: MethodId::getCardState, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 3, id: MethodId::getCVM, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 4, id: MethodId::getSecureChannel, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 5, id: MethodId::lockCard, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 6, id: MethodId::terminateCard, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 7, id: MethodId::setATRHistBytes, signature: Signature(4), is_static: true, static_token: true },
    ApiMethod { token: 8, id: MethodId::setCardContentState, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 9, id: MethodId::getRegistryEntry, signature: Signature(0), is_static: true, static_token: true },
    ApiMethod { token: 10, id: MethodId::getService, signature: Signature(0), is_static: true, static_token: true },
];

const CLASSES_A00000015100: [ApiClass; 12] = [
    ApiClass { token: 0, id: ClassId::Application, is_interface: true, supers: &SUPERS_A00000015100_0, methods: &METHODS_A00000015100_0 },
    ApiClass { token: 1, id: ClassId::CVM, is_interface: true, supers: &SUPERS_A00000015100_1, methods: &METHODS_A00000015100_1 },
    ApiClass { token: 2, id: ClassId::SecureChannel, is_interface: true, supers: &SUPERS_A00000015100_2, methods: &METHODS_A00000015100_2 },
    ApiClass { token: 3, id: ClassId::GPSystem, is_interface: false, supers: &SUPERS_A00000015100_3, methods: &METHODS_A00000015100_3 },
    ApiClass { token: 4, id: ClassId::GPRegistryEntry, is_interface: true, supers: &SUPERS_A00000015100_4, methods: &METHODS_A00000015100_4 },
    ApiClass { token: 5, id: ClassId::GlobalService, is_interface: true, supers: &SUPERS_A00000015100_5, methods: &METHODS_A00000015100_5 },
    ApiClass { token: 6, id: ClassId::SecureChannelx, is_interface: true, supers: &SUPERS_A00000015100_6, methods: &METHODS_A00000015100_6 },
    ApiClass { token: 7, id: ClassId::Authority, is_interface: true, supers: &SUPERS_A00000015100_7, methods: &METHODS_A00000015100_7 },
    ApiClass { token: 8, id: ClassId::Personalization, is_interface: true, supers: &SUPERS_A00000015100_8, methods: &METHODS_A00000015100_8 },
    ApiClass { token: 9, id: ClassId::HTTPAdministration, is_interface: true, supers: &SUPERS_A00000015100_9, methods: &METHODS_A00000015100_9 },
    ApiClass { token: 10, id: ClassId::HTTPReportListener, is_interface: true, supers: &SUPERS_A00000015100_10, methods: &METHODS_A00000015100_10 },
    ApiClass { token: 11, id: ClassId::SecureChannelx2, is_interface: true, supers: &SUPERS_A00000015100_11, methods: &METHODS_A00000015100_11 },
];

/// Every package this engine knows how to resolve an import against.
pub const PACKAGES: [ApiPackage; 6] = [
    ApiPackage { aid: &[0xa0, 0x00, 0x00, 0x00, 0x62, 0x00, 0x01], id: PackageId::java_lang, major: 1, minor: 0, classes: &CLASSES_A0000000620001 },
    ApiPackage { aid: &[0xa0, 0x00, 0x00, 0x00, 0x62, 0x01, 0x01], id: PackageId::javacard_framework, major: 1, minor: 6, classes: &CLASSES_A0000000620101 },
    ApiPackage { aid: &[0xa0, 0x00, 0x00, 0x00, 0x62, 0x01, 0x02], id: PackageId::javacard_security, major: 1, minor: 6, classes: &CLASSES_A0000000620102 },
    ApiPackage { aid: &[0xa0, 0x00, 0x00, 0x00, 0x62, 0x02, 0x01], id: PackageId::javacardx_crypto, major: 1, minor: 6, classes: &CLASSES_A0000000620201 },
    ApiPackage { aid: &[0xa0, 0x00, 0x00, 0x00, 0x62, 0x02, 0x09], id: PackageId::javacardx_apdu, major: 1, minor: 0, classes: &CLASSES_A0000000620209 },
    ApiPackage { aid: &[0xa0, 0x00, 0x00, 0x01, 0x51, 0x00], id: PackageId::org_globalplatform, major: 1, minor: 5, classes: &CLASSES_A00000015100 },
];
