#if CASE_METHOD_ROWS_LIMIT || CASE_METHOD_ROWS_BOUNDARY
namespace MicroCard.AnalyzerCases;

public static class MethodRows
{
    // Cases.cs contributes ten emitted methods, so these fixtures total 256 or 257.
    public static void M000() { }
    public static void M001() { }
    public static void M002() { }
    public static void M003() { }
    public static void M004() { }
    public static void M005() { }
    public static void M006() { }
    public static void M007() { }
    public static void M008() { }
    public static void M009() { }
    public static void M010() { }
    public static void M011() { }
    public static void M012() { }
    public static void M013() { }
    public static void M014() { }
    public static void M015() { }
    public static void M016() { }
    public static void M017() { }
    public static void M018() { }
    public static void M019() { }
    public static void M020() { }
    public static void M021() { }
    public static void M022() { }
    public static void M023() { }
    public static void M024() { }
    public static void M025() { }
    public static void M026() { }
    public static void M027() { }
    public static void M028() { }
    public static void M029() { }
    public static void M030() { }
    public static void M031() { }
    public static void M032() { }
    public static void M033() { }
    public static void M034() { }
    public static void M035() { }
    public static void M036() { }
    public static void M037() { }
    public static void M038() { }
    public static void M039() { }
    public static void M040() { }
    public static void M041() { }
    public static void M042() { }
    public static void M043() { }
    public static void M044() { }
    public static void M045() { }
    public static void M046() { }
    public static void M047() { }
    public static void M048() { }
    public static void M049() { }
    public static void M050() { }
    public static void M051() { }
    public static void M052() { }
    public static void M053() { }
    public static void M054() { }
    public static void M055() { }
    public static void M056() { }
    public static void M057() { }
    public static void M058() { }
    public static void M059() { }
    public static void M060() { }
    public static void M061() { }
    public static void M062() { }
    public static void M063() { }
    public static void M064() { }
    public static void M065() { }
    public static void M066() { }
    public static void M067() { }
    public static void M068() { }
    public static void M069() { }
    public static void M070() { }
    public static void M071() { }
    public static void M072() { }
    public static void M073() { }
    public static void M074() { }
    public static void M075() { }
    public static void M076() { }
    public static void M077() { }
    public static void M078() { }
    public static void M079() { }
    public static void M080() { }
    public static void M081() { }
    public static void M082() { }
    public static void M083() { }
    public static void M084() { }
    public static void M085() { }
    public static void M086() { }
    public static void M087() { }
    public static void M088() { }
    public static void M089() { }
    public static void M090() { }
    public static void M091() { }
    public static void M092() { }
    public static void M093() { }
    public static void M094() { }
    public static void M095() { }
    public static void M096() { }
    public static void M097() { }
    public static void M098() { }
    public static void M099() { }
    public static void M100() { }
    public static void M101() { }
    public static void M102() { }
    public static void M103() { }
    public static void M104() { }
    public static void M105() { }
    public static void M106() { }
    public static void M107() { }
    public static void M108() { }
    public static void M109() { }
    public static void M110() { }
    public static void M111() { }
    public static void M112() { }
    public static void M113() { }
    public static void M114() { }
    public static void M115() { }
    public static void M116() { }
    public static void M117() { }
    public static void M118() { }
    public static void M119() { }
    public static void M120() { }
    public static void M121() { }
    public static void M122() { }
    public static void M123() { }
    public static void M124() { }
    public static void M125() { }
    public static void M126() { }
    public static void M127() { }
    public static void M128() { }
    public static void M129() { }
    public static void M130() { }
    public static void M131() { }
    public static void M132() { }
    public static void M133() { }
    public static void M134() { }
    public static void M135() { }
    public static void M136() { }
    public static void M137() { }
    public static void M138() { }
    public static void M139() { }
    public static void M140() { }
    public static void M141() { }
    public static void M142() { }
    public static void M143() { }
    public static void M144() { }
    public static void M145() { }
    public static void M146() { }
    public static void M147() { }
    public static void M148() { }
    public static void M149() { }
    public static void M150() { }
    public static void M151() { }
    public static void M152() { }
    public static void M153() { }
    public static void M154() { }
    public static void M155() { }
    public static void M156() { }
    public static void M157() { }
    public static void M158() { }
    public static void M159() { }
    public static void M160() { }
    public static void M161() { }
    public static void M162() { }
    public static void M163() { }
    public static void M164() { }
    public static void M165() { }
    public static void M166() { }
    public static void M167() { }
    public static void M168() { }
    public static void M169() { }
    public static void M170() { }
    public static void M171() { }
    public static void M172() { }
    public static void M173() { }
    public static void M174() { }
    public static void M175() { }
    public static void M176() { }
    public static void M177() { }
    public static void M178() { }
    public static void M179() { }
    public static void M180() { }
    public static void M181() { }
    public static void M182() { }
    public static void M183() { }
    public static void M184() { }
    public static void M185() { }
    public static void M186() { }
    public static void M187() { }
    public static void M188() { }
    public static void M189() { }
    public static void M190() { }
    public static void M191() { }
    public static void M192() { }
    public static void M193() { }
    public static void M194() { }
    public static void M195() { }
    public static void M196() { }
    public static void M197() { }
    public static void M198() { }
    public static void M199() { }
    public static void M200() { }
    public static void M201() { }
    public static void M202() { }
    public static void M203() { }
    public static void M204() { }
    public static void M205() { }
    public static void M206() { }
    public static void M207() { }
    public static void M208() { }
    public static void M209() { }
    public static void M210() { }
    public static void M211() { }
    public static void M212() { }
    public static void M213() { }
    public static void M214() { }
    public static void M215() { }
    public static void M216() { }
    public static void M217() { }
    public static void M218() { }
    public static void M219() { }
    public static void M220() { }
    public static void M221() { }
    public static void M222() { }
    public static void M223() { }
    public static void M224() { }
    public static void M225() { }
    public static void M226() { }
    public static void M227() { }
    public static void M228() { }
    public static void M229() { }
    public static void M230() { }
    public static void M231() { }
    public static void M232() { }
    public static void M233() { }
    public static void M234() { }
    public static void M235() { }
    public static void M236() { }
    public static void M237() { }
    public static void M238() { }
    public static void M239() { }
    public static void M240() { }
    public static void M241() { }
    public static void M242() { }
    public static void M243() { }
    public static void M244() { }
    public static void M245() { }
#if CASE_METHOD_ROWS_LIMIT
    public static void M246() { }
#endif
}
#endif
