#if CASE_TYPE_ROWS_LIMIT || CASE_TYPE_ROWS_BOUNDARY
namespace MicroCard.AnalyzerCases;

// The ordinary build contributes six source types; MC04 also emits the required module TypeDef.
public static class Type000 { }
public static class Type001 { }
public static class Type002 { }
public static class Type003 { }
public static class Type004 { }
public static class Type005 { }
public static class Type006 { }
public static class Type007 { }
public static class Type008 { }
public static class Type009 { }
public static class Type010 { }
public static class Type011 { }
public static class Type012 { }
public static class Type013 { }
public static class Type014 { }
public static class Type015 { }
public static class Type016 { }
public static class Type017 { }
public static class Type018 { }
public static class Type019 { }
public static class Type020 { }
public static class Type021 { }
public static class Type022 { }
public static class Type023 { }
public static class Type024 { }
public static class Type025 { }
public static class Type026 { }
public static class Type027 { }
public static class Type028 { }
public static class Type029 { }
public static class Type030 { }
public static class Type031 { }
public static class Type032 { }
public static class Type033 { }
public static class Type034 { }
public static class Type035 { }
public static class Type036 { }
public static class Type037 { }
public static class Type038 { }
public static class Type039 { }
public static class Type040 { }
public static class Type041 { }
public static class Type042 { }
public static class Type043 { }
public static class Type044 { }
public static class Type045 { }
public static class Type046 { }
public static class Type047 { }
public static class Type048 { }
public static class Type049 { }
public static class Type050 { }
public static class Type051 { }
public static class Type052 { }
public static class Type053 { }
public static class Type054 { }
public static class Type055 { }
public static class Type056 { }
public static class Type057 { }
public static class Type058 { }
public static class Type059 { }
public static class Type060 { }
public static class Type061 { }
public static class Type062 { }
public static class Type063 { }
public static class Type064 { }
public static class Type065 { }
public static class Type066 { }
public static class Type067 { }
public static class Type068 { }
public static class Type069 { }
public static class Type070 { }
public static class Type071 { }
public static class Type072 { }
public static class Type073 { }
public static class Type074 { }
public static class Type075 { }
public static class Type076 { }
public static class Type077 { }
public static class Type078 { }
public static class Type079 { }
public static class Type080 { }
public static class Type081 { }
public static class Type082 { }
public static class Type083 { }
public static class Type084 { }
public static class Type085 { }
public static class Type086 { }
public static class Type087 { }
public static class Type088 { }
public static class Type089 { }
public static class Type090 { }
public static class Type091 { }
public static class Type092 { }
public static class Type093 { }
public static class Type094 { }
public static class Type095 { }
public static class Type096 { }
public static class Type097 { }
public static class Type098 { }
public static class Type099 { }
public static class Type100 { }
public static class Type101 { }
public static class Type102 { }
public static class Type103 { }
public static class Type104 { }
public static class Type105 { }
public static class Type106 { }
public static class Type107 { }
public static class Type108 { }
public static class Type109 { }
public static class Type110 { }
public static class Type111 { }
public static class Type112 { }
public static class Type113 { }
public static class Type114 { }
public static class Type115 { }
public static class Type116 { }
public static class Type117 { }
public static class Type118 { }
public static class Type119 { }
public static class Type120 { }
public static class Type121 { }
public static class Type122 { }
public static class Type123 { }
public static class Type124 { }
public static class Type125 { }
public static class Type126 { }
public static class Type127 { }
public static class Type128 { }
public static class Type129 { }
public static class Type130 { }
public static class Type131 { }
public static class Type132 { }
public static class Type133 { }
public static class Type134 { }
public static class Type135 { }
public static class Type136 { }
public static class Type137 { }
public static class Type138 { }
public static class Type139 { }
public static class Type140 { }
public static class Type141 { }
public static class Type142 { }
public static class Type143 { }
public static class Type144 { }
public static class Type145 { }
public static class Type146 { }
public static class Type147 { }
public static class Type148 { }
public static class Type149 { }
public static class Type150 { }
public static class Type151 { }
public static class Type152 { }
public static class Type153 { }
public static class Type154 { }
public static class Type155 { }
public static class Type156 { }
public static class Type157 { }
public static class Type158 { }
public static class Type159 { }
public static class Type160 { }
public static class Type161 { }
public static class Type162 { }
public static class Type163 { }
public static class Type164 { }
public static class Type165 { }
public static class Type166 { }
public static class Type167 { }
public static class Type168 { }
public static class Type169 { }
public static class Type170 { }
public static class Type171 { }
public static class Type172 { }
public static class Type173 { }
public static class Type174 { }
public static class Type175 { }
public static class Type176 { }
public static class Type177 { }
public static class Type178 { }
public static class Type179 { }
public static class Type180 { }
public static class Type181 { }
public static class Type182 { }
public static class Type183 { }
public static class Type184 { }
public static class Type185 { }
public static class Type186 { }
public static class Type187 { }
public static class Type188 { }
public static class Type189 { }
public static class Type190 { }
public static class Type191 { }
public static class Type192 { }
public static class Type193 { }
public static class Type194 { }
public static class Type195 { }
public static class Type196 { }
public static class Type197 { }
public static class Type198 { }
public static class Type199 { }
public static class Type200 { }
public static class Type201 { }
public static class Type202 { }
public static class Type203 { }
public static class Type204 { }
public static class Type205 { }
public static class Type206 { }
public static class Type207 { }
public static class Type208 { }
public static class Type209 { }
public static class Type210 { }
public static class Type211 { }
public static class Type212 { }
public static class Type213 { }
public static class Type214 { }
public static class Type215 { }
public static class Type216 { }
public static class Type217 { }
public static class Type218 { }
public static class Type219 { }
public static class Type220 { }
public static class Type221 { }
public static class Type222 { }
public static class Type223 { }
public static class Type224 { }
public static class Type225 { }
public static class Type226 { }
public static class Type227 { }
public static class Type228 { }
public static class Type229 { }
public static class Type230 { }
public static class Type231 { }
public static class Type232 { }
public static class Type233 { }
public static class Type234 { }
public static class Type235 { }
public static class Type236 { }
public static class Type237 { }
public static class Type238 { }
public static class Type239 { }
public static class Type240 { }
public static class Type241 { }
public static class Type242 { }
public static class Type243 { }
public static class Type244 { }
public static class Type245 { }
#if CASE_TYPE_ROWS_LIMIT
public static class Type246 { }
#endif
#endif
