// Generated by scripts/generate_mc04_opcodes.py. Do not edit.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Operand {
    None,
    I8,
    VarU8,
    I32,
    BranchI8,
    BranchI32,
    SwitchI32,
    MethodToken,
    FieldToken,
    TypeToken,
}
#[allow(non_camel_case_types, clippy::enum_variant_names)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Pop {
    Pop0,
    Pop1,
    Pop1_pop1,
    Popi,
    Popref,
    Popref_pop1,
    Popref_popi,
    Popref_popi_popi,
    Varpop,
}
#[allow(non_camel_case_types, clippy::enum_variant_names)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Push {
    Push0,
    Push1,
    Push1_push1,
    Pushi,
    Pushref,
    Varpush,
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Flow {
    Branch,
    Call,
    Cond_Branch,
    Next,
    Return,
}
#[derive(Clone, Copy)]
pub struct Opcode {
    pub operand: Operand,
    pub token_tables: u16,
    pub pop: Pop,
    pub push: Push,
    pub flow: Flow,
    /// Includes the opcode prefix; zero denotes the variable-length switch.
    pub fixed_length: u8,
}
// Index zero rejects unsupported instructions, including unused FE prefixes.
const PRIMARY: [u8; 256] = [
    1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 0,
    0, 4, 0, 5, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8,
    9, 0, 0, 0, 0, 10, 3, 0, 11, 0, 12, 13, 14, 14, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 16, 17, 17, 18, 18, 18, 18, 18,
    18, 18, 18, 18, 18, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 20, 20, 20, 20, 20, 20, 20, 20,
    20, 20, 20, 20, 20, 21, 21, 22, 22, 22, 0, 0, 0, 22, 0, 11,
    0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 24, 0, 25, 0, 0,
    0, 0, 22, 22, 22, 0, 22, 22, 22, 0, 0, 0, 0, 26, 27, 0,
    0, 28, 0, 0, 28, 0, 0, 0, 0, 0, 0, 0, 29, 0, 29, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 22, 22, 22, 22, 22, 22, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 22, 22, 0, 0, 0, 20, 20, 20, 20, 20, 20, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
];

const EXTENDED: [u8; 6] = [
    0, 30, 30, 30, 30, 30,
];

const PROFILES: [Opcode; 30] = [
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Pop0,
        push: Push::Push0,
        flow: Flow::Next,
        fixed_length: 1,
    },
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Pop0,
        push: Push::Push1,
        flow: Flow::Next,
        fixed_length: 1,
    },
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Pop1,
        push: Push::Push0,
        flow: Flow::Next,
        fixed_length: 1,
    },
    Opcode {
        operand: Operand::VarU8,
        token_tables: 0x0000,
        pop: Pop::Pop0,
        push: Push::Push1,
        flow: Flow::Next,
        fixed_length: 2,
    },
    Opcode {
        operand: Operand::VarU8,
        token_tables: 0x0000,
        pop: Pop::Pop1,
        push: Push::Push0,
        flow: Flow::Next,
        fixed_length: 2,
    },
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Pop0,
        push: Push::Pushref,
        flow: Flow::Next,
        fixed_length: 1,
    },
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Pop0,
        push: Push::Pushi,
        flow: Flow::Next,
        fixed_length: 1,
    },
    Opcode {
        operand: Operand::I8,
        token_tables: 0x0000,
        pop: Pop::Pop0,
        push: Push::Pushi,
        flow: Flow::Next,
        fixed_length: 2,
    },
    Opcode {
        operand: Operand::I32,
        token_tables: 0x0000,
        pop: Pop::Pop0,
        push: Push::Pushi,
        flow: Flow::Next,
        fixed_length: 5,
    },
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Pop1,
        push: Push::Push1_push1,
        flow: Flow::Next,
        fixed_length: 1,
    },
    Opcode {
        operand: Operand::MethodToken,
        token_tables: 0x0440,
        pop: Pop::Varpop,
        push: Push::Varpush,
        flow: Flow::Call,
        fixed_length: 4,
    },
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Varpop,
        push: Push::Push0,
        flow: Flow::Return,
        fixed_length: 1,
    },
    Opcode {
        operand: Operand::BranchI8,
        token_tables: 0x0000,
        pop: Pop::Pop0,
        push: Push::Push0,
        flow: Flow::Branch,
        fixed_length: 2,
    },
    Opcode {
        operand: Operand::BranchI8,
        token_tables: 0x0000,
        pop: Pop::Popi,
        push: Push::Push0,
        flow: Flow::Cond_Branch,
        fixed_length: 2,
    },
    Opcode {
        operand: Operand::BranchI8,
        token_tables: 0x0000,
        pop: Pop::Pop1_pop1,
        push: Push::Push0,
        flow: Flow::Cond_Branch,
        fixed_length: 2,
    },
    Opcode {
        operand: Operand::BranchI32,
        token_tables: 0x0000,
        pop: Pop::Pop0,
        push: Push::Push0,
        flow: Flow::Branch,
        fixed_length: 5,
    },
    Opcode {
        operand: Operand::BranchI32,
        token_tables: 0x0000,
        pop: Pop::Popi,
        push: Push::Push0,
        flow: Flow::Cond_Branch,
        fixed_length: 5,
    },
    Opcode {
        operand: Operand::BranchI32,
        token_tables: 0x0000,
        pop: Pop::Pop1_pop1,
        push: Push::Push0,
        flow: Flow::Cond_Branch,
        fixed_length: 5,
    },
    Opcode {
        operand: Operand::SwitchI32,
        token_tables: 0x0000,
        pop: Pop::Popi,
        push: Push::Push0,
        flow: Flow::Cond_Branch,
        fixed_length: 0,
    },
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Pop1_pop1,
        push: Push::Push1,
        flow: Flow::Next,
        fixed_length: 1,
    },
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Pop1,
        push: Push::Push1,
        flow: Flow::Next,
        fixed_length: 1,
    },
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Pop1,
        push: Push::Pushi,
        flow: Flow::Next,
        fixed_length: 1,
    },
    Opcode {
        operand: Operand::MethodToken,
        token_tables: 0x0440,
        pop: Pop::Varpop,
        push: Push::Pushref,
        flow: Flow::Call,
        fixed_length: 4,
    },
    Opcode {
        operand: Operand::FieldToken,
        token_tables: 0x0010,
        pop: Pop::Popref,
        push: Push::Push1,
        flow: Flow::Next,
        fixed_length: 4,
    },
    Opcode {
        operand: Operand::FieldToken,
        token_tables: 0x0010,
        pop: Pop::Popref_pop1,
        push: Push::Push0,
        flow: Flow::Next,
        fixed_length: 4,
    },
    Opcode {
        operand: Operand::TypeToken,
        token_tables: 0x0006,
        pop: Pop::Popi,
        push: Push::Pushref,
        flow: Flow::Next,
        fixed_length: 4,
    },
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Popref,
        push: Push::Pushi,
        flow: Flow::Next,
        fixed_length: 1,
    },
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Popref_popi,
        push: Push::Pushi,
        flow: Flow::Next,
        fixed_length: 1,
    },
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Popref_popi_popi,
        push: Push::Push0,
        flow: Flow::Next,
        fixed_length: 1,
    },
    Opcode {
        operand: Operand::None,
        token_tables: 0x0000,
        pop: Pop::Pop1_pop1,
        push: Push::Pushi,
        flow: Flow::Next,
        fixed_length: 2,
    },
];

pub fn lookup(value: u16) -> Option<&'static Opcode> {
    let index = if value <= 0xff {
        PRIMARY[usize::from(value)]
    } else {
        *EXTENDED.get(usize::from(value.checked_sub(0xfe00)?))?
    };
    PROFILES.get(usize::from(index.checked_sub(1)?))
}
