// Generated by scripts/generate_mc04_schema.py. Do not edit.
pub const ALLOWED_TABLES: u64 = 0x0000000900001457;
pub const SECTION_TABLES: u8 = 1;
pub const SECTION_STRINGS: u8 = 2;
pub const SECTION_BLOB: u8 = 3;
pub const SECTION_CODE: u8 = 4;
pub const TABLE_MODULE: u8 = 0;
pub const MAX_MODULE_ROWS: u16 = 1;
pub const TABLE_TYPEREF: u8 = 1;
pub const MAX_TYPEREF_ROWS: u16 = 256;
pub const TABLE_TYPEDEF: u8 = 2;
pub const MAX_TYPEDEF_ROWS: u16 = 253;
pub const TABLE_FIELD: u8 = 4;
pub const MAX_FIELD_ROWS: u16 = 1022;
pub const TABLE_METHODDEF: u8 = 6;
pub const MAX_METHODDEF_ROWS: u16 = 256;
pub const TABLE_MEMBERREF: u8 = 10;
pub const MAX_MEMBERREF_ROWS: u16 = 256;
pub const TABLE_CUSTOMATTRIBUTE: u8 = 12;
pub const MAX_CUSTOMATTRIBUTE_ROWS: u16 = 256;
pub const TABLE_ASSEMBLY: u8 = 32;
pub const MAX_ASSEMBLY_ROWS: u16 = 1;
pub const TABLE_ASSEMBLYREF: u8 = 35;
pub const MAX_ASSEMBLYREF_ROWS: u16 = 17;
pub fn max_rows(table: u8) -> Option<u16> {
    Some(match table {
        0 => 1,
        1 => 256,
        2 => 253,
        4 => 1022,
        6 => 256,
        10 => 256,
        12 => 256,
        32 => 1,
        35 => 17,
        _ => return None,
    })
}

#[rustfmt::skip]
pub fn row_width(table: u8, string_width: usize, blob_width: usize, rows: &[u16; 64]) -> Option<usize> {
    Some(match table {
        0 => string_width,
        1 => 2 + string_width + string_width,
        2 => 4 + string_width + string_width + 2 + (if rows[4] <= 255 { 1 } else { 2 }) + (if rows[6] <= 255 { 1 } else { 2 }),
        4 => 2 + string_width + blob_width,
        6 => 4 + 2 + 2 + string_width + blob_width,
        10 => 2 + string_width + blob_width,
        12 => 2 + 2 + blob_width,
        32 => 2 + 2 + 2 + 2 + 4 + string_width,
        35 => 2 + 2 + 2 + 2 + 4 + blob_width + string_width + string_width + blob_width,
        _ => return None,
    })
}
