// Generated by scripts/generate_mc04_abi.py from abi/mc04.toml. Do not edit.
//! Stable native capability identifiers shared by package and domain validation.
use crate::{Error, Result};

pub const CATALOG_SHA256: &str = "fbf27e9a7355a1d62755412dfad24122b24708b1c0c76dbbef17936d8ed0cad0";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Signature {
    pub arguments: u8,
    pub returns: bool,
}

pub const fn capability(id: u8) -> u8 {
    match id {
        55 => 46,
        56 => 47,
        57 => 48,
        58 => 46,
        59 => 46,
        60 => 46,
        _ => id,
    }
}

pub fn signature(id: u8) -> Result<Signature> {
    let (arguments, returns) = match id {
        2 => (1, false),
        5 => (0, true),
        6 => (2, false),
        7 => (1, true),
        8 => (2, false),
        9 => (0, true),
        10 => (0, true),
        11 => (0, true),
        12 => (4, false),
        13 => (3, false),
        20 => (1, true),
        22 => (2, true),
        23 => (1, true),
        24 => (1, false),
        25 => (2, true),
        26 => (2, true),
        27 => (3, true),
        28 => (3, true),
        29 => (4, true),
        30 => (4, true),
        31 => (1, true),
        32 => (2, false),
        33 => (1, false),
        34 => (1, true),
        35 => (1, true),
        36 => (4, true),
        37 => (3, true),
        38 => (2, true),
        39 => (3, false),
        40 => (9, false),
        41 => (4, true),
        42 => (1, true),
        43 => (4, false),
        44 => (7, true),
        45 => (2, true),
        49 => (5, true),
        50 => (1, true),
        51 => (6, true),
        52 => (4, false),
        53 => (5, true),
        54 => (6, true),
        55 => (0, false),
        56 => (0, false),
        57 => (0, false),
        58 => (0, true),
        59 => (1, true),
        60 => (1, true),
        _ => return Err(Error::Native),
    };
    Ok(Signature { arguments, returns })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_capability_table_is_exact() {
        const VALID: &[u8] = &[
            2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
            59, 60,
        ];
        for id in 0..=u8::MAX {
            assert_eq!(
                signature(id).is_ok(),
                VALID.contains(&id),
                "capability {id}"
            );
        }
        assert_eq!(capability(55), 46);
        assert_eq!(capability(56), 47);
        assert_eq!(capability(57), 48);
        assert_eq!(capability(58), 46);
        assert_eq!(capability(60), 46);
    }
}
