// Generated by scripts/generate_mc04_abi.py from abi/mc04.toml. Do not edit.
//! Stable native capability identifiers shared by package and domain validation.
use crate::{Error, Result};

pub const CATALOG_SHA256: &str = "fbf27e9a7355a1d62755412dfad24122b24708b1c0c76dbbef17936d8ed0cad0";

/// Native operation IDs from the MC04 ABI catalog.
pub mod id {
    pub const RESPONSE_SERVICE_SET_STATUS: u8 = 2;
    pub const RANDOM_SERVICE_GET_INT32: u8 = 5;
    pub const RUNTIME_SERVICE_WRITE_HARDWARE: u8 = 6;
    pub const STORAGE_SERVICE_GET_INT32: u8 = 7;
    pub const STORAGE_SERVICE_SET_INT32: u8 = 8;
    pub const SECURE_CHANNEL_SERVICE_SECURITY_LEVEL: u8 = 9;
    pub const SECURE_CHANNEL_SERVICE_IS_AUTHENTICATED: u8 = 10;
    pub const COMMAND_SERVICE_LENGTH: u8 = 11;
    pub const COMMAND_SERVICE_COPY_TO: u8 = 12;
    pub const RESPONSE_SERVICE_WRITE: u8 = 13;
    pub const RUNTIME_SERVICE_SHA256: u8 = 20;
    pub const KEY_SERVICE_GENERATE: u8 = 22;
    pub const KEY_SERVICE_OPEN: u8 = 23;
    pub const KEY_SERVICE_DELETE: u8 = 24;
    pub const KEY_HANDLE_HMAC_SHA256: u8 = 25;
    pub const KEY_HANDLE_AES_CMAC: u8 = 26;
    pub const KEY_HANDLE_ENCRYPT_CBC: u8 = 27;
    pub const KEY_HANDLE_DECRYPT_CBC: u8 = 28;
    pub const KEY_HANDLE_ENCRYPT_CCM: u8 = 29;
    pub const KEY_HANDLE_DECRYPT_CCM: u8 = 30;
    pub const STORAGE_SERVICE_GET_BYTES: u8 = 31;
    pub const STORAGE_SERVICE_SET_BYTES_2_ARGS: u8 = 32;
    pub const STORAGE_SERVICE_DELETE_BYTES: u8 = 33;
    pub const STORAGE_SERVICE_CONTAINS_BYTES: u8 = 34;
    pub const KEY_HANDLE_EXPORT_P256_PUBLIC_KEY: u8 = 35;
    pub const KEY_HANDLE_SIGN_P256: u8 = 36;
    pub const RUNTIME_SERVICE_VERIFY_P256: u8 = 37;
    pub const KEY_HANDLE_DERIVE_P256: u8 = 38;
    pub const RANDOM_SERVICE_FILL: u8 = 39;
    pub const CREDENTIAL_SERVICE_CREATE: u8 = 40;
    pub const CREDENTIAL_SERVICE_VERIFY: u8 = 41;
    pub const CREDENTIAL_SERVICE_IS_VERIFIED: u8 = 42;
    pub const CREDENTIAL_SERVICE_CHANGE: u8 = 43;
    pub const CREDENTIAL_SERVICE_UNBLOCK: u8 = 44;
    pub const CREDENTIAL_SERVICE_RETRIES_REMAINING: u8 = 45;
    pub const RUNTIME_SERVICE_SHA256_INTO: u8 = 49;
    pub const RANDOM_SERVICE_GET_BYTES: u8 = 50;
    pub const RUNTIME_SERVICE_FIXED_TIME_EQUALS: u8 = 51;
    pub const STORAGE_SERVICE_SET_BYTES_4_ARGS: u8 = 52;
    pub const BUFFERS_COPY: u8 = 53;
    pub const TLV_TRY_READ: u8 = 54;
    pub const TRANSACTION_SCOPE_RUNTIME_BEGIN: u8 = 55;
    pub const TRANSACTION_SCOPE_RUNTIME_COMMIT: u8 = 56;
    pub const TRANSACTION_SCOPE_RUNTIME_ABORT: u8 = 57;
    pub const TRANSACTION_RUNTIME_CURRENT: u8 = 58;
    pub const TRANSACTION_RUNTIME_INFORMATION: u8 = 59;
    pub const TRANSACTION_INFORMATION_RUNTIME_STATUS: u8 = 60;
}

pub const CAPABILITIES: &[u8] = &[
    2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
    36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
];

pub const fn valid_capability(id: u8) -> bool {
    matches!(
        id,
        2 | 5
            | 6
            | 7
            | 8
            | 9
            | 10
            | 11
            | 12
            | 13
            | 20
            | 22
            | 23
            | 24
            | 25
            | 26
            | 27
            | 28
            | 29
            | 30
            | 31
            | 32
            | 33
            | 34
            | 35
            | 36
            | 37
            | 38
            | 39
            | 40
            | 41
            | 42
            | 43
            | 44
            | 45
            | 46
            | 47
            | 48
            | 49
            | 50
            | 51
            | 52
            | 53
            | 54
    )
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Signature {
    pub arguments: u8,
    pub returns: bool,
}

pub const fn capability(id: u8) -> u8 {
    match id {
        55 => 46,
        56 => 47,
        57 => 48,
        58 => 46,
        59 => 46,
        60 => 46,
        _ => id,
    }
}

pub fn signature(id: u8) -> Result<Signature> {
    let (arguments, returns) = match id {
        2 => (1, false),
        5 => (0, true),
        6 => (2, false),
        7 => (1, true),
        8 => (2, false),
        9 => (0, true),
        10 => (0, true),
        11 => (0, true),
        12 => (4, false),
        13 => (3, false),
        20 => (1, true),
        22 => (2, true),
        23 => (1, true),
        24 => (1, false),
        25 => (2, true),
        26 => (2, true),
        27 => (3, true),
        28 => (3, true),
        29 => (4, true),
        30 => (4, true),
        31 => (1, true),
        32 => (2, false),
        33 => (1, false),
        34 => (1, true),
        35 => (1, true),
        36 => (4, true),
        37 => (3, true),
        38 => (2, true),
        39 => (3, false),
        40 => (9, false),
        41 => (4, true),
        42 => (1, true),
        43 => (4, false),
        44 => (7, true),
        45 => (2, true),
        49 => (5, true),
        50 => (1, true),
        51 => (6, true),
        52 => (4, false),
        53 => (5, true),
        54 => (6, true),
        55 => (0, false),
        56 => (0, false),
        57 => (0, false),
        58 => (0, true),
        59 => (1, true),
        60 => (1, true),
        _ => return Err(Error::Native),
    };
    Ok(Signature { arguments, returns })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_capability_table_is_exact() {
        const VALID: &[u8] = &[
            2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
            59, 60,
        ];
        for id in 0..=u8::MAX {
            assert_eq!(
                signature(id).is_ok(),
                VALID.contains(&id),
                "capability {id}"
            );
        }
        for id in 0..=u8::MAX {
            assert_eq!(
                valid_capability(id),
                CAPABILITIES.contains(&id),
                "capability {id}"
            );
        }
        assert_eq!(capability(55), 46);
        assert_eq!(capability(56), 47);
        assert_eq!(capability(57), 48);
        assert_eq!(capability(58), 46);
        assert_eq!(capability(60), 46);
    }
}
