// Generated by scripts/generate_mc04_abi.py from abi/mc04.toml. Do not edit.
using System;
using System.Collections.Generic;

namespace MicroCard.Build
{
    internal sealed class Mc04AbiMember
    {
        internal Mc04AbiMember(string assembly, string ns, string owner, string name,
            bool instance, string[] parameters, string result, int capability,
            string lowering, string sideEffect, string[] profiles)
        {
            Assembly = assembly; Namespace = ns; Owner = owner; Name = name;
            Instance = instance; Parameters = parameters; Result = result;
            Capability = capability; Lowering = lowering; SideEffect = sideEffect;
            Profiles = profiles;
        }
        internal string Assembly { get; }
        internal string Namespace { get; }
        internal string Owner { get; }
        internal string Name { get; }
        internal bool Instance { get; }
        internal string[] Parameters { get; }
        internal string Result { get; }
        internal int Capability { get; }
        internal string Lowering { get; }
        internal string SideEffect { get; }
        internal string[] Profiles { get; }
    }

    internal static class Mc04Abi
    {
        internal const string CatalogSha256 = "fbf27e9a7355a1d62755412dfad24122b24708b1c0c76dbbef17936d8ed0cad0";
        internal const string FrameworkAssembly = "MicroCard.Framework";
        internal const string FrameworkNamespace = "MicroCard.Framework";
        internal const string FrameworkIdentitySha256 = "89311954345F8652190CF4EF9F24F04AE5EF771E6F4840B831EC44FC4FFFA7F7";
        private static readonly Mc04AbiMember[] Members =
        {
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "AssemblyContext", "get_Current",
                false, Array.Empty<string>(), "ref:MicroCard.Framework.AssemblyContext", -1,
                "current-context", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "AssemblyContext", "get_Command",
                true, Array.Empty<string>(), "ref:MicroCard.Framework.CommandService", -1,
                "service", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "AssemblyContext", "get_Response",
                true, Array.Empty<string>(), "ref:MicroCard.Framework.ResponseService", -1,
                "service", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "AssemblyContext", "get_Storage",
                true, Array.Empty<string>(), "ref:MicroCard.Framework.StorageService", -1,
                "storage-service", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "AssemblyContext", "get_Keys",
                true, Array.Empty<string>(), "ref:MicroCard.Framework.KeyService", -1,
                "service", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "AssemblyContext", "get_Random",
                true, Array.Empty<string>(), "ref:MicroCard.Framework.RandomService", -1,
                "service", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "AssemblyContext", "get_SecureChannel",
                true, Array.Empty<string>(), "ref:MicroCard.Framework.SecureChannelService", -1,
                "service", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "AssemblyContext", "get_Credentials",
                true, Array.Empty<string>(), "ref:MicroCard.Framework.CredentialService", -1,
                "service", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "AssemblyContext", "get_Runtime",
                true, Array.Empty<string>(), "ref:MicroCard.Framework.RuntimeService", -1,
                "service", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "ResponseService", "SetStatus",
                true, new[] { "enum:MicroCard.Framework.StatusWord" }, "void", 2,
                "native", "irreversible", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "RandomService", "GetInt32",
                true, Array.Empty<string>(), "int32", 5,
                "native", "random", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "RuntimeService", "WriteHardware",
                true, new[] { "int32", "int32" }, "void", 6,
                "native", "irreversible", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "StorageService", "GetInt32",
                true, new[] { "enum:MicroCard.Framework.StorageId" }, "int32", 7,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "StorageService", "SetInt32",
                true, new[] { "enum:MicroCard.Framework.StorageId", "int32" }, "void", 8,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "SecureChannelService", "get_SecurityLevel",
                true, Array.Empty<string>(), "enum:MicroCard.Framework.SecurityLevel", 9,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "SecureChannelService", "get_IsAuthenticated",
                true, Array.Empty<string>(), "bool", 10,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CommandService", "get_Length",
                true, Array.Empty<string>(), "int32", 11,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CommandService", "CopyTo",
                true, new[] { "byte[]", "int32", "int32", "int32" }, "void", 12,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "ResponseService", "Write",
                true, new[] { "byte[]", "int32", "int32" }, "void", 13,
                "native", "irreversible", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "RuntimeService", "Sha256",
                true, new[] { "byte[]" }, "byte[]", 20,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyService", "Generate",
                true, new[] { "enum:MicroCard.Framework.KeySlot", "enum:MicroCard.Framework.KeyAlgorithm" }, "ref:MicroCard.Framework.KeyHandle", 22,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyService", "Open",
                true, new[] { "enum:MicroCard.Framework.KeySlot" }, "ref:MicroCard.Framework.KeyHandle", 23,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyService", "Delete",
                true, new[] { "enum:MicroCard.Framework.KeySlot" }, "void", 24,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "HmacSha256",
                true, new[] { "byte[]" }, "byte[]", 25,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "AesCmac",
                true, new[] { "byte[]" }, "byte[]", 26,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "EncryptCbc",
                true, new[] { "byte[]", "byte[]" }, "byte[]", 27,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "DecryptCbc",
                true, new[] { "byte[]", "byte[]" }, "byte[]", 28,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "EncryptCcm",
                true, new[] { "byte[]", "byte[]", "byte[]" }, "byte[]", 29,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "DecryptCcm",
                true, new[] { "byte[]", "byte[]", "byte[]" }, "byte[]", 30,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "StorageService", "GetBytes",
                true, new[] { "enum:MicroCard.Framework.StorageId" }, "byte[]", 31,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "StorageService", "SetBytes",
                true, new[] { "enum:MicroCard.Framework.StorageId", "byte[]" }, "void", 32,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "StorageService", "DeleteBytes",
                true, new[] { "enum:MicroCard.Framework.StorageId" }, "void", 33,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "StorageService", "ContainsBytes",
                true, new[] { "enum:MicroCard.Framework.StorageId" }, "bool", 34,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "ExportP256PublicKey",
                true, Array.Empty<string>(), "byte[]", 35,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "SignP256",
                true, new[] { "byte[]", "int32", "int32" }, "byte[]", 36,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "RuntimeService", "VerifyP256",
                true, new[] { "byte[]", "byte[]", "byte[]" }, "bool", 37,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "DeriveP256",
                true, new[] { "byte[]" }, "byte[]", 38,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "RandomService", "Fill",
                true, new[] { "byte[]", "int32", "int32" }, "void", 39,
                "native", "random", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CredentialService", "Create",
                true, new[] { "enum:MicroCard.Framework.CredentialSlot", "byte[]", "int32", "int32", "int32", "byte[]", "int32", "int32", "int32" }, "void", 40,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CredentialService", "Verify",
                true, new[] { "enum:MicroCard.Framework.CredentialSlot", "byte[]", "int32", "int32" }, "bool", 41,
                "native", "security-state", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CredentialService", "IsVerified",
                true, new[] { "enum:MicroCard.Framework.CredentialSlot" }, "bool", 42,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CredentialService", "Change",
                true, new[] { "enum:MicroCard.Framework.CredentialSlot", "byte[]", "int32", "int32" }, "void", 43,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CredentialService", "Unblock",
                true, new[] { "enum:MicroCard.Framework.CredentialSlot", "byte[]", "int32", "int32", "byte[]", "int32", "int32" }, "bool", 44,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CredentialService", "RetriesRemaining",
                true, new[] { "enum:MicroCard.Framework.CredentialSlot", "int32" }, "int32", 45,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "RuntimeService", "Sha256Into",
                true, new[] { "byte[]", "int32", "int32", "byte[]", "int32" }, "int32", 49,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "RandomService", "GetBytes",
                true, new[] { "int32" }, "byte[]", 50,
                "native", "random", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "RuntimeService", "FixedTimeEquals",
                true, new[] { "byte[]", "int32", "int32", "byte[]", "int32", "int32" }, "bool", 51,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "StorageService", "SetBytes",
                true, new[] { "enum:MicroCard.Framework.StorageId", "byte[]", "int32", "int32" }, "void", 52,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "Buffers", "Copy",
                false, new[] { "byte[]", "int32", "byte[]", "int32", "int32" }, "bool", 53,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "Tlv", "TryRead",
                false, new[] { "byte[]", "int32", "int32", "int32[]", "int32", "bool" }, "bool", 54,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "TransactionScopeRuntime", "Begin",
                false, Array.Empty<string>(), "void", 46,
                "native", "transaction-control", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "TransactionScopeRuntime", "Commit",
                false, Array.Empty<string>(), "void", 47,
                "native", "transaction-control", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "TransactionScopeRuntime", "Abort",
                false, Array.Empty<string>(), "void", 48,
                "native", "transaction-control", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "TransactionRuntime", "Current",
                false, Array.Empty<string>(), "ref:MicroCard.Framework.TransactionRuntime", 46,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "TransactionRuntime", "Information",
                true, Array.Empty<string>(), "ref:MicroCard.Framework.TransactionInformationRuntime", 46,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "TransactionInformationRuntime", "Status",
                true, Array.Empty<string>(), "int32", 46,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "RuntimeIntrinsics", "Sha256",
                false, new[] { "byte[]" }, "byte[]", 20,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "RuntimeIntrinsics", "RandomBytes",
                false, new[] { "int32" }, "byte[]", 50,
                "native", "random", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "System.Security.Cryptography", "System.Security.Cryptography", "SHA256", "HashData",
                false, new[] { "byte[]" }, "byte[]", 20,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "System.Security.Cryptography", "System.Security.Cryptography", "RandomNumberGenerator", "GetBytes",
                false, new[] { "int32" }, "byte[]", 50,
                "native", "random", new[] { "mc04-1.0" }),
        };

        internal static bool ContainsName(string assembly, string ns, string owner, string name)
        {
            foreach (var member in Members)
                if (member.Assembly == assembly && member.Namespace == ns &&
                    member.Owner == owner && member.Name == name)
                    return true;
            return false;
        }

        internal static Mc04AbiMember Find(string assembly, string ns, string owner,
            string name, bool instance, IReadOnlyList<string> parameters, string result)
        {
            foreach (var member in Members)
            {
                if (member.Assembly != assembly || member.Namespace != ns ||
                    member.Owner != owner || member.Name != name ||
                    member.Instance != instance || member.Result != result ||
                    member.Parameters.Length != parameters.Count)
                    continue;
                var equal = true;
                for (var index = 0; index < parameters.Count; index++)
                    equal &= member.Parameters[index] == parameters[index];
                if (equal) return member;
            }
            return null;
        }
    }
}
