// Generated by scripts/generate_mc04_abi.py from abi/mc04.toml. Do not edit.
using System;
using System.Collections.Generic;

namespace MicroCard.Build
{
    internal sealed class Mc04AbiMember
    {
        internal Mc04AbiMember(string assembly, string ns, string owner, string name,
            bool instance, string[] parameters, string result, int capability,
            string lowering, string sideEffect, string[] profiles)
        {
            Assembly = assembly; Namespace = ns; Owner = owner; Name = name;
            Instance = instance; Parameters = parameters; Result = result;
            Capability = capability; Lowering = lowering; SideEffect = sideEffect;
            Profiles = profiles;
        }
        internal string Assembly { get; }
        internal string Namespace { get; }
        internal string Owner { get; }
        internal string Name { get; }
        internal bool Instance { get; }
        internal string[] Parameters { get; }
        internal string Result { get; }
        internal int Capability { get; }
        internal string Lowering { get; }
        internal string SideEffect { get; }
        internal string[] Profiles { get; }
    }

    internal static class Mc04Abi
    {
        internal const string CatalogSha256 = "fb91d13b52460aae3f399480b8f112716837379042e872f84581f3492b19c75a";
        internal const string FrameworkAssembly = "MicroCard.Framework";
        internal const string FrameworkNamespace = "MicroCard.Framework";
        internal const string FrameworkIdentitySha256 = "E9B276DC4459E6FFB37F9119874B5053B14CD0B3484A01C70316DD80FB08365A";
        private static readonly Mc04AbiMember[] Members =
        {
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "SecurityDomain", "get_Current",
                false, Array.Empty<string>(), "ref:MicroCard.Framework.SecurityDomain", -1,
                "current-domain", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "SecurityDomain", "get_Keys",
                true, Array.Empty<string>(), "ref:MicroCard.Framework.DomainKeys", -1,
                "domain-keys", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "SecurityDomain", "get_Store",
                true, Array.Empty<string>(), "ref:MicroCard.Framework.DomainStorage", -1,
                "domain-storage", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "ResponseApdu", "SetStatus",
                false, new[] { "int32" }, "void", 2,
                "native", "irreversible", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainStore", "GetInt32",
                false, new[] { "int32" }, "int32", 3,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainStore", "SetInt32",
                false, new[] { "int32", "int32" }, "void", 4,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "RandomNumber", "GetInt32",
                false, Array.Empty<string>(), "int32", 5,
                "native", "random", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "Hardware", "Write",
                false, new[] { "int32", "int32" }, "void", 6,
                "native", "irreversible", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainStorage", "GetInt32",
                true, new[] { "int32" }, "int32", 7,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainStorage", "SetInt32",
                true, new[] { "int32", "int32" }, "void", 8,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "SecureChannel", "get_SecurityLevel",
                false, Array.Empty<string>(), "int32", 9,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "SecureChannel", "get_IsAuthenticated",
                false, Array.Empty<string>(), "bool", 10,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CommandApdu", "get_Length",
                false, Array.Empty<string>(), "int32", 11,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CommandApdu", "CopyTo",
                false, new[] { "byte[]", "int32", "int32", "int32" }, "void", 12,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "ResponseApdu", "Write",
                false, new[] { "byte[]", "int32", "int32" }, "void", 13,
                "native", "irreversible", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "Cryptography", "Sha256",
                false, new[] { "byte[]" }, "byte[]", 20,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainKeys", "Generate",
                true, new[] { "int32", "int32" }, "ref:MicroCard.Framework.KeyHandle", 22,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainKeys", "Open",
                true, new[] { "int32" }, "ref:MicroCard.Framework.KeyHandle", 23,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainKeys", "Delete",
                true, new[] { "int32" }, "void", 24,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "HmacSha256",
                true, new[] { "byte[]" }, "byte[]", 25,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "AesCmac",
                true, new[] { "byte[]" }, "byte[]", 26,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "EncryptCbc",
                true, new[] { "byte[]", "byte[]" }, "byte[]", 27,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "DecryptCbc",
                true, new[] { "byte[]", "byte[]" }, "byte[]", 28,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "EncryptCcm",
                true, new[] { "byte[]", "byte[]", "byte[]" }, "byte[]", 29,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "DecryptCcm",
                true, new[] { "byte[]", "byte[]", "byte[]" }, "byte[]", 30,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainStorage", "GetBytes",
                true, new[] { "int32" }, "byte[]", 31,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainStorage", "SetBytes",
                true, new[] { "int32", "byte[]" }, "void", 32,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainStorage", "DeleteBytes",
                true, new[] { "int32" }, "void", 33,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainStorage", "ContainsBytes",
                true, new[] { "int32" }, "bool", 34,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "ExportP256PublicKey",
                true, Array.Empty<string>(), "byte[]", 35,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "SignP256",
                true, new[] { "byte[]", "int32", "int32" }, "byte[]", 36,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "Cryptography", "VerifyP256",
                false, new[] { "byte[]", "byte[]", "byte[]" }, "bool", 37,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "KeyHandle", "DeriveP256",
                true, new[] { "byte[]" }, "byte[]", 38,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "Cryptography", "FillRandom",
                false, new[] { "byte[]", "int32", "int32" }, "void", 39,
                "native", "random", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CredentialNative", "Create",
                false, new[] { "int32", "byte[]", "int32", "int32", "int32", "byte[]", "int32", "int32", "int32" }, "void", 40,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CredentialNative", "Verify",
                false, new[] { "int32", "byte[]", "int32", "int32" }, "bool", 41,
                "native", "security-state", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CredentialNative", "IsVerified",
                false, new[] { "int32" }, "bool", 42,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CredentialNative", "Change",
                false, new[] { "int32", "byte[]", "int32", "int32" }, "void", 43,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CredentialNative", "Unblock",
                false, new[] { "int32", "byte[]", "int32", "int32", "byte[]", "int32", "int32" }, "bool", 44,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "CredentialNative", "RetriesRemaining",
                false, new[] { "int32", "int32" }, "int32", 45,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainStorage", "BeginTransaction",
                true, Array.Empty<string>(), "void", 46,
                "native", "transaction-control", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainStorage", "CommitTransaction",
                true, Array.Empty<string>(), "void", 47,
                "native", "transaction-control", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainStorage", "AbortTransaction",
                true, Array.Empty<string>(), "void", 48,
                "native", "transaction-control", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "Cryptography", "Sha256Into",
                false, new[] { "byte[]", "int32", "int32", "byte[]", "int32" }, "int32", 49,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "Cryptography", "RandomBytes",
                false, new[] { "int32" }, "byte[]", 50,
                "native", "random", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "Cryptography", "FixedTimeEquals",
                false, new[] { "byte[]", "int32", "int32", "byte[]", "int32", "int32" }, "bool", 51,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "DomainStorage", "SetBytes",
                true, new[] { "int32", "byte[]", "int32", "int32" }, "void", 52,
                "native", "transactional", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "Buffers", "Copy",
                false, new[] { "byte[]", "int32", "byte[]", "int32", "int32" }, "bool", 53,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "Tlv", "TryRead",
                false, new[] { "byte[]", "int32", "int32", "int32[]", "int32", "int32" }, "bool", 54,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "TransactionScopeRuntime", "Begin",
                false, Array.Empty<string>(), "void", 46,
                "native", "transaction-control", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "TransactionScopeRuntime", "Commit",
                false, Array.Empty<string>(), "void", 47,
                "native", "transaction-control", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "TransactionScopeRuntime", "Abort",
                false, Array.Empty<string>(), "void", 48,
                "native", "transaction-control", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "TransactionRuntime", "Current",
                false, Array.Empty<string>(), "ref:MicroCard.Framework.TransactionRuntime", 46,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "TransactionRuntime", "Information",
                true, Array.Empty<string>(), "ref:MicroCard.Framework.TransactionInformationRuntime", 46,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "MicroCard.Framework", "MicroCard.Framework", "TransactionInformationRuntime", "Status",
                true, Array.Empty<string>(), "int32", 46,
                "native", "read", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "System.Security.Cryptography", "System.Security.Cryptography", "SHA256", "HashData",
                false, new[] { "byte[]" }, "byte[]", 20,
                "native", "none", new[] { "mc04-1.0" }),
            new Mc04AbiMember(
                "System.Security.Cryptography", "System.Security.Cryptography", "RandomNumberGenerator", "GetBytes",
                false, new[] { "int32" }, "byte[]", 50,
                "native", "random", new[] { "mc04-1.0" }),
        };

        internal static bool ContainsName(string assembly, string ns, string owner, string name)
        {
            foreach (var member in Members)
                if (member.Assembly == assembly && member.Namespace == ns &&
                    member.Owner == owner && member.Name == name)
                    return true;
            return false;
        }

        internal static Mc04AbiMember Find(string assembly, string ns, string owner,
            string name, bool instance, IReadOnlyList<string> parameters, string result)
        {
            foreach (var member in Members)
            {
                if (member.Assembly != assembly || member.Namespace != ns ||
                    member.Owner != owner || member.Name != name ||
                    member.Instance != instance || member.Result != result ||
                    member.Parameters.Length != parameters.Count)
                    continue;
                var equal = true;
                for (var index = 0; index < parameters.Count; index++)
                    equal &= member.Parameters[index] == parameters[index];
                if (equal) return member;
            }
            return null;
        }
    }
}
