#ifndef MICROCARD_PSA_CONFIG_H
#define MICROCARD_PSA_CONFIG_H

#define MBEDTLS_PSA_CRYPTO_C
#define PSA_WANT_KEY_TYPE_AES 1
#define PSA_WANT_ALG_CMAC 1
#define PSA_WANT_ALG_SHA_256 1
#define PSA_USE_CC3XX_MAC_DRIVER 1

#ifdef MICROCARD_CC310_HMAC
#define PSA_WANT_KEY_TYPE_HMAC 1
#define PSA_WANT_ALG_HMAC 1
#endif

#ifdef MICROCARD_CC310_AES
#define PSA_WANT_ALG_ECB_NO_PADDING 1
#define PSA_USE_CC3XX_CIPHER_DRIVER 1
#endif

#ifdef MICROCARD_CC310_CBC
#define PSA_WANT_ALG_CBC_NO_PADDING 1
#define PSA_USE_CC3XX_CIPHER_DRIVER 1
#endif

#ifdef MICROCARD_CC310_CCM
#define PSA_WANT_ALG_CCM 1
#define PSA_USE_CC3XX_AEAD_DRIVER 1
#endif

#ifdef MICROCARD_CC310_P256
#define PSA_WANT_ALG_ECDH 1
#define PSA_WANT_ALG_DETERMINISTIC_ECDSA 1
#define PSA_WANT_ECC_SECP_R1_256 1
#define PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_IMPORT 1
#define PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_EXPORT 1
#define PSA_WANT_KEY_TYPE_ECC_PUBLIC_KEY 1
#define PSA_USE_CC3XX_KEY_AGREEMENT_DRIVER 1
#define PSA_USE_CC3XX_ASYMMETRIC_SIGNATURE_DRIVER 1
#define PSA_USE_CC3XX_HASH_DRIVER 1
#define PSA_USE_CC3XX_KEY_MANAGEMENT_DRIVER 1
#endif

#endif
