// Generated by scripts/generate_mc04_schema.py. Do not edit.
internal static class Mc04Schema
{
    internal const ulong AllowedTables = 0x0000000900001457UL;
    internal const byte Module = 0;
    internal const ushort MaxModuleRows = 1;
    internal const byte TypeRef = 1;
    internal const ushort MaxTypeRefRows = 256;
    internal const byte TypeDef = 2;
    internal const ushort MaxTypeDefRows = 253;
    internal const byte Field = 4;
    internal const ushort MaxFieldRows = 1022;
    internal const byte MethodDef = 6;
    internal const ushort MaxMethodDefRows = 256;
    internal const byte MemberRef = 10;
    internal const ushort MaxMemberRefRows = 256;
    internal const byte CustomAttribute = 12;
    internal const ushort MaxCustomAttributeRows = 256;
    internal const byte Assembly = 32;
    internal const ushort MaxAssemblyRows = 1;
    internal const byte AssemblyRef = 35;
    internal const ushort MaxAssemblyRefRows = 17;
}
