[package]
name = "microcard-core"
version.workspace = true
edition.workspace = true
license.workspace = true
[features]
fuzzing = []
hal-conformance = []
[dependencies]
base64ct.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
ed25519-dalek.workspace = true
p256.workspace = true
aes = { version = "0.8", default-features = false }
cmac = { version = "0.7", default-features = false }
hmac = { version = "0.12", default-features = false }
ccm = { version = "0.5", default-features = false, features=["alloc"] }
subtle = { version = "2", default-features = false }
zeroize = { version = "1", default-features = false, features = ["derive"] }
