<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../managed/MicroCard.Build/VersionConstraint.cs" Link="VersionConstraint.cs" />
    <Compile Include="../../managed/MicroCard.Build/EmbeddedIdentifier.cs" Link="EmbeddedIdentifier.cs" />
  </ItemGroup>
</Project>
