"""Analyzer expectations shared by focused and checkpoint validation."""
import json
from validation_common import ROOT, run

CASES = {'CASE_TRANSACTION_SCOPE': None, 'CASE_TRANSACTION_CURRENT': None, 'CASE_TRANSACTION_CURRENT_SET': 'MCA0004', 'CASE_TRANSACTION_LIFECYCLE': 'MCA0005', 'CASE_LANGUAGE': 'MCA0001', 'CASE_ASYNC_METHOD': 'MCA0001', 'CASE_USING_DECLARATION': 'MCA0001', 'CASE_TYPEOF': 'MCA0001', 'CASE_INIT_PROPERTY': 'MCA0001', 'CASE_TYPE': 'MCA0002', 'CASE_REF_RETURN': 'MCA0003', 'CASE_SHAPE': 'MCA0003', 'CASE_STATIC_CONSTRUCTOR': 'MCA0003', 'CASE_INTERFACE': 'MCA0003', 'CASE_NESTED_TYPE': 'MCA0003', 'CASE_STATIC_FIELD': 'MCA0003', 'CASE_FIELD_TYPE': 'MCA0003', 'CASE_METHOD_IMPL_FLAGS': 'MCA0003', 'CASE_INHERITANCE': 'MCA0003', 'CASE_LITERAL_FIELD_TYPE': 'MCA0003', 'CASE_EVENT': 'MCA0003', 'CASE_STATIC_AUTO_PROPERTY': 'MCA0003', 'CASE_AUTO_PROPERTY_FIELD': 'MCA0003', 'CASE_EXTERNAL': 'MCA0004', 'CASE_SYSTEM_SHA256_OVERLOAD': 'MCA0004', 'CASE_SYSTEM_RNG_OVERLOAD': 'MCA0004', 'CASE_LIFECYCLE': 'MCA0005', 'CASE_EXPORT': 'MCA0006', 'CASE_DEPENDENCY': 'MCA0007', 'CASE_REFERENCE_ALIAS': 'MCA0007', 'CASE_REFERENCE_RESERVED': 'MCA0007', 'CASE_DEVICE_IDENTITY': 'MCA0007', 'CASE_IDENTIFIER': 'MCA0007', 'CASE_TRANSACTION': 'MCA0008', 'CASE_CALL_GRAPH': 'MCA0009', 'CASE_CALL_DEPTH': 'MCA0009', 'CASE_LOCALS': 'MCA0010', 'CASE_ALLOCATION': 'MCA0011', 'CASE_ALLOCATION_OVERHEAD': 'MCA0011', 'CASE_LOOP_ALLOCATION': 'MCA0012', 'CASE_LOOP_OBJECT_ALLOCATION': 'MCA0012', 'CASE_LOOP_COLLECTION_ALLOCATION': 'MCA0012', 'CASE_AGGREGATE_ALLOCATION': 'MCA0013', 'CASE_CALL_ALLOCATION': 'MCA0014', 'CASE_SWITCH_LIMIT': 'MCA0015', 'CASE_CALL_OBJECTS': 'MCA0016', 'CASE_PARAMETERS': 'MCA0017', 'CASE_DEPENDENCY_LIMIT': 'MCA0018', 'CASE_ENTRY_LIMIT': 'MCA0019', 'CASE_METHOD_ROWS_LIMIT': 'MCA0020', 'CASE_TYPE_ROWS_LIMIT': 'MCA0021', 'CASE_FIELD_ROWS_LIMIT': 'MCA0022', 'CASE_STORAGE_SCHEMA': 'MCA0024', 'CASE_STORAGE_ACCESS': 'MCA0025', '': None, 'CASE_ALLOCATION_BOUNDARY': None, 'CASE_SWITCH_BOUNDARY': None, 'CASE_PARAMETERS_BOUNDARY': None, 'CASE_DEPENDENCY_BOUNDARY': None, 'CASE_ENTRY_BOUNDARY': None, 'CASE_METHOD_ROWS_BOUNDARY': None, 'CASE_TYPE_ROWS_BOUNDARY': None, 'CASE_FIELD_ROWS_BOUNDARY': None}


def run_analyzer_cases(emission=None, prebuilt=False):
    path = ROOT / "work/analyzer-cases.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(CASES, indent=2) + "\n")
    if not prebuilt:
        run("dotnet", "build", "tests/AnalyzerHarness", "-c", "Release", "--nologo", "--verbosity", "quiet")
    run("dotnet", str(ROOT / "tests/AnalyzerHarness/bin/Release/net10.0/AnalyzerHarness.dll"),
        str(ROOT / "tests/AnalyzerCases"), str(path), *([str(emission)] if emission else []))
