#!/usr/bin/env python3
"""Generate opcode allowlists and the normative MC04 opcode appendix."""
import argparse, json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "format/mc04-opcodes.json"

RUST_OPERANDS = {
    "none": "None", "i8": "I8", "var_u8": "VarU8", "i32": "I32",
    "branch_i8": "BranchI8", "branch_i32": "BranchI32", "switch_i32": "SwitchI32",
    "method_token": "MethodToken", "field_token": "FieldToken", "type_token": "TypeToken",
}
TABLES = {"TypeRef": 1, "TypeDef": 2, "Field": 4, "MethodDef": 6, "MemberRef": 10}
OPERAND_BYTES = {"none": 0, "i8": 1, "var_u8": 1, "i32": 4,
                 "branch_i8": 1, "branch_i32": 4, "method_token": 3,
                 "field_token": 3, "type_token": 3}

def rust(schema):
    pops = sorted({opcode["pop"] for opcode in schema["opcodes"]})
    pushes = sorted({opcode["push"] for opcode in schema["opcodes"]})
    flows = sorted({opcode["flow"] for opcode in schema["opcodes"]})
    lines = [
        "// Generated by scripts/generate_mc04_opcodes.py. Do not edit.",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub enum Operand {", "    None,", "    I8,", "    VarU8,", "    I32,", "    BranchI8,", "    BranchI32,", "    SwitchI32,", "    MethodToken,", "    FieldToken,", "    TypeToken,", "}",
        "#[allow(non_camel_case_types, clippy::enum_variant_names)]", "#[derive(Clone, Copy, Debug, PartialEq, Eq)]", "pub enum Pop {", *[f"    {value}," for value in pops], "}",
        "#[allow(non_camel_case_types, clippy::enum_variant_names)]", "#[derive(Clone, Copy, Debug, PartialEq, Eq)]", "pub enum Push {", *[f"    {value}," for value in pushes], "}",
        "#[allow(non_camel_case_types)]", "#[derive(Clone, Copy, Debug, PartialEq, Eq)]", "pub enum Flow {", *[f"    {value}," for value in flows], "}",
        "#[derive(Clone, Copy)]",
        "pub struct Opcode {", "    pub operand: Operand,", "    pub token_tables: u16,", "    pub pop: Pop,", "    pub push: Push,", "    pub flow: Flow,",
        "    /// Includes the opcode prefix; zero denotes the variable-length switch.",
        "    pub fixed_length: u8,", "}",
    ]
    profiles = []
    primary = [0] * 256
    extended = [0] * (1 + max((o["value"] & 255 for o in schema["opcodes"] if o["value"] > 255), default=0))
    for opcode in schema["opcodes"]:
        mask = sum(1 << TABLES[name] for name in opcode["token_tables"])
        value = opcode["value"]
        if not (0 <= value < 0xfe or 0xfe00 <= value <= 0xfeff):
            raise ValueError(f"invalid opcode encoding: {value:#x}")
        length = 0 if opcode["operand"] == "switch_i32" else (2 if value > 255 else 1) + OPERAND_BYTES[opcode["operand"]]
        profile = (RUST_OPERANDS[opcode["operand"]], mask, opcode["pop"], opcode["push"], opcode["flow"], length)
        if profile not in profiles:
            profiles.append(profile)
        (extended if value > 255 else primary)[value & 255] = profiles.index(profile) + 1
    if len(profiles) > 255 or max(p[1] for p in profiles) > 65535:
        raise ValueError("opcode metadata exceeds compact table bounds")
    lines += ["// Index zero rejects unsupported instructions, including unused FE prefixes."]
    for name, indexes in (("PRIMARY", primary), ("EXTENDED", extended)):
        lines += [f"const {name}: [u8; {len(indexes)}] = ["]
        lines += ["    " + ", ".join(str(n) for n in indexes[i:i+16]) + "," for i in range(0, len(indexes), 16)]
        lines += ["];", ""]
    lines += [f"const PROFILES: [Opcode; {len(profiles)}] = ["]
    for operand, mask, pop, push, flow, length in profiles:
        lines += ["    Opcode {", f"        operand: Operand::{operand},", f"        token_tables: 0x{mask:04x},", f"        pop: Pop::{pop},", f"        push: Push::{push},", f"        flow: Flow::{flow},", f"        fixed_length: {length},", "    },"]
    lines += ["];", "", "pub fn lookup(value: u16) -> Option<&'static Opcode> {",
              "    let index = if value <= 0xff {", "        PRIMARY[usize::from(value)]",
              "    } else {", "        *EXTENDED.get(usize::from(value.checked_sub(0xfe00)?))?", "    };",
              "    PROFILES.get(usize::from(index.checked_sub(1)?))", "}", ""]
    return "\n".join(lines)

def csharp(schema):
    lines = [
        "// Generated by scripts/generate_mc04_opcodes.py. Do not edit.",
        "internal static class Mc04Opcodes",
        "{",
        "    internal static bool IsAllowed(short value) => unchecked((ushort)value) switch",
        "    {",
    ]
    for opcode in schema["opcodes"]:
        lines.append(f"        0x{opcode['value']:04X} => true, // {opcode['name']}")
    lines += ["        _ => false,", "    };", "}", ""]
    return "\n".join(lines)

def markdown(schema):
    lines = [
        "# MC04 CIL opcode appendix", "",
        "Generated from `format/mc04-opcodes.json`. Opcode bytes, operand forms, stack behavior and flow names follow ECMA-335 Partition III. Metadata operands use MC04's compact `table:u8, row:u16` token. Other operand widths retain their CIL encoding.", "",
        "| Bytes | CIL name | MC04 operand | Token tables | Pop | Push | Flow |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for opcode in schema["opcodes"]:
        value = opcode["value"]
        encoded = f"FE {value & 0xff:02X}" if value > 0xff else f"{value:02X}"
        targets = ", ".join(opcode["token_tables"]) or "-"
        lines.append(f"| `{encoded}` | `{opcode['name']}` | `{opcode['operand']}` | {targets} | `{opcode['pop']}` | `{opcode['push']}` | `{opcode['flow']}` |")
    lines += ["", f"`switch_i32` is limited to {schema['switch_limit']} targets. Any opcode absent from this appendix is rejected before activation.", ""]
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = json.loads(SOURCE.read_text())
    values = [opcode["value"] for opcode in schema["opcodes"]]
    if values != sorted(values) or len(values) != len(set(values)):
        raise ValueError("opcode values must be unique and sorted")
    outputs = {
        ROOT / "crates/microcard-core/src/mc04_opcodes.rs": rust(schema),
        ROOT / "managed/MicroCard.Tool/Mc04Opcodes.g.cs": csharp(schema),
        ROOT / "docs/MC04_OPCODES.md": markdown(schema),
    }
    stale = []
    for path, content in outputs.items():
        content = content.rstrip() + "\n"
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if stale:
        print("stale generated MC04 opcode files: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
