#!/usr/bin/env python3
"""Generate the Java Card opcode tables and their appendix from format/jcvm-opcodes.json."""
import argparse
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "format/jcvm-opcodes.json"
RUST = ROOT / "crates/microcard-engine-jcvm/src/jcvm_opcodes.rs"
MARKDOWN = ROOT / "docs/JCVM_OPCODES.md"
BANNER = "Generated by scripts/generate_jcvm_opcodes.py. Do not edit."


def table(schema: dict, key, default, width: int = 16) -> list[str]:
    """One 256-entry table, laid out so a reviewer can find an opcode by its row."""
    values = [default] * 256
    for opcode in schema["opcodes"]:
        values[opcode["value"]] = key(opcode)
    lines = []
    for start in range(0, 256, width):
        row = ", ".join(str(value) for value in values[start: start + width])
        lines.append(f"    {row},")
    return lines


def branch_width(opcode: dict) -> int:
    """Width of the branch offset this instruction carries, or zero when it has none.

    A branch offset is signed and counts from the address of the opcode itself, which is
    what makes every target checkable against the instruction boundaries.
    """
    operands = opcode["operands"]
    if operands[:1] == ["branch"]:
        return 1
    if operands[:2] == ["branchbyte1", "branchbyte2"]:
        return 2
    return 0


def rust(schema: dict) -> str:
    variable = [op["name"] for op in schema["opcodes"] if op["length"] is None]
    lines = [
        f"// {BANNER}",
        f"// Source: {schema['source']}",
        "",
        "/// Whether this build knows the instruction at all.",
        "///",
        "/// The reserved opcodes cannot appear in a CAP file, JCVM section 7.2, so they are",
        "/// undefined here along with every value the specification never assigned.",
        "pub const DEFINED: [bool; 256] = [",
        *table(schema, lambda op: "true", "false", width=8),
        "];",
        "",
        "/// Total instruction size in bytes, including the opcode. Zero means the size",
        f"/// depends on the operands, which is true of {', '.join(variable)}.",
        "pub const FIXED_LENGTH: [u8; 256] = [",
        *table(schema, lambda op: op["length"] or 0, 0),
        "];",
        "",
        "/// Whether the instruction needs 32-bit integer support.",
        "///",
        "/// A package whose header leaves ACC_INT clear can never reach one of these, so the",
        "/// verifier refuses them and the interpreter needs no arm for them.",
        "pub const INT_ONLY: [bool; 256] = [",
        *table(schema, lambda op: "true" if op["int_only"] else "false", "false", width=8),
        "];",
        "",
        "/// Whether control continues to the instruction that follows this one.",
        "///",
        "/// False for the returns, athrow, the unconditional jumps and the switches. A",
        "/// conditional branch both falls through and branches.",
        "pub const FALLS_THROUGH: [bool; 256] = [",
        *table(schema, lambda op: "true" if op["falls_through"] else "false", "false", width=8),
        "];",
        "",
        "/// Width in bytes of the branch offset the instruction carries, or zero.",
        "///",
        "/// The offset is signed and counts from the address of the opcode, JCVM section 7.5.",
        "pub const BRANCH_WIDTH: [u8; 256] = [",
        *table(schema, branch_width, 0),
        "];",
        "",
        "/// Mnemonics, for diagnostics and tests only.",
        "#[cfg(any(test, feature = \"diagnostics\"))]",
        "pub const NAME: [&str; 256] = [",
    ]
    names = ['""'] * 256
    for opcode in schema["opcodes"]:
        names[opcode["value"]] = f'"{opcode["name"]}"'
    for reserved in schema["reserved"]:
        names[reserved["value"]] = f'"{reserved["name"]}"'
    for start in range(0, 256, 8):
        lines.append("    " + ", ".join(names[start: start + 8]) + ",")
    lines += ["];", ""]
    return "\n".join(lines)


def markdown(schema: dict) -> str:
    lines = [
        "# Java Card instruction set",
        "",
        f"{BANNER}",
        "",
        f"Source: {schema['source']}",
        "",
        f"{len(schema['opcodes'])} instructions, plus the two reserved opcodes that cannot "
        "appear in a CAP file. A variable-length entry has no size here because its size "
        "depends on its operands.",
        "",
        "| Opcode | Mnemonic | Operands | Bytes | Needs int | Branch width | Falls through |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for opcode in schema["opcodes"]:
        operands = ", ".join(opcode["operands"]) or "none"
        length = opcode["length"] or "variable"
        needs = "yes" if opcode["int_only"] else "no"
        branch = branch_width(opcode) or ""
        through = "yes" if opcode["falls_through"] else "no"
        lines.append(f"| `{opcode['value']:#04x}` | `{opcode['name']}` | {operands} | {length} | {needs} | {branch} | {through} |")
    lines += ["", "| Opcode | Reserved mnemonic |", "| --- | --- |"]
    for reserved in schema["reserved"]:
        lines.append(f"| `{reserved['value']:#04x}` | `{reserved['name']}` |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify the outputs are current")
    arguments = parser.parse_args()
    schema = json.loads(SOURCE.read_text())
    outputs = {RUST: rust(schema), MARKDOWN: markdown(schema)}
    stale = [path for path, text in outputs.items()
             if not path.exists() or path.read_text() != text]
    if arguments.check:
        if stale:
            raise SystemExit("Stale generated files:\n  "
                             + "\n  ".join(str(path.relative_to(ROOT)) for path in stale))
    else:
        for path, text in outputs.items():
            path.write_text(text)
    print(f"PASS: {len(schema['opcodes'])} Java Card opcodes, {len(outputs)} generated files")


if __name__ == "__main__":
    main()
