#!/usr/bin/env python3
"""Read Java Card export files into format/jcvm-api.json, and generate the Rust tables.

A CAP file names everything it borrows by token. A method token means nothing on its own:
its meaning comes from the export file of the package that declares it. Without that
mapping the engine cannot tell which API method an applet is calling.

Export files are Oracle build outputs and stay out of this repository. This reads them once
into a committed table, so the build never needs the Oracle tools and a reviewer can see
exactly which token means which method.

Run with --from-exp and a directory of export files to refresh the table, and with --check
to verify the generated Rust matches it.
"""
import argparse
import json
import pathlib
import struct

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "format/jcvm-api.json"
RUST = ROOT / "crates/microcard-engine-jcvm/src/jcvm_api.rs"
MARKDOWN = ROOT / "docs/JCVM_API.md"
BANNER = "Generated by scripts/generate_jcvm_api.py. Do not edit."

MAGIC = 0x00FACADE
CONSTANT_UTF8 = 1
CONSTANT_INTEGER = 3
CONSTANT_CLASSREF = 7
CONSTANT_PACKAGE = 13

# Access flags, JCVM Table 5-3 and 5-6.
ACC_INTERFACE = 0x0200
ACC_STATIC = 0x0008

# The packages the profile commits to. Anything else in the directory is skipped, so a
# refresh does not quietly widen what the engine claims to implement.
WANTED = {
    "A0000000620001": "java.lang",
    "A0000000620101": "javacard.framework",
    "A0000000620102": "javacard.security",
    "A0000000620201": "javacardx.crypto",
    "A0000000620209": "javacardx.apdu",
    "A00000015100": "org.globalplatform",
}


class Reader:
    def __init__(self, data: bytes):
        self.data = data
        self.at = 0

    def take(self, count: int) -> bytes:
        if self.at + count > len(self.data):
            raise ValueError("export file ends mid structure")
        value = self.data[self.at: self.at + count]
        self.at += count
        return value

    def u1(self) -> int:
        return self.take(1)[0]

    def u2(self) -> int:
        return struct.unpack(">H", self.take(2))[0]

    def u4(self) -> int:
        return struct.unpack(">I", self.take(4))[0]


def constant_pool(reader: Reader) -> list:
    """Every constant, in the order the file stores them, JCVM section 5.6."""
    count = reader.u2()
    pool = []
    for _ in range(count):
        tag = reader.u1()
        if tag == CONSTANT_PACKAGE:
            flags = reader.u1()
            name_index = reader.u2()
            minor, major = reader.u1(), reader.u1()
            aid = reader.take(reader.u1())
            pool.append({
                "tag": tag, "flags": flags, "name": name_index,
                "version": f"{major}.{minor}", "aid": aid.hex().upper(),
            })
        elif tag == CONSTANT_CLASSREF:
            pool.append({"tag": tag, "name": reader.u2()})
        elif tag == CONSTANT_INTEGER:
            pool.append({"tag": tag, "value": reader.u4()})
        elif tag == CONSTANT_UTF8:
            pool.append({"tag": tag, "text": reader.take(reader.u2()).decode("utf-8")})
        else:
            raise ValueError(f"unknown export constant tag {tag}")
    return pool


def text(pool: list, index: int) -> str:
    entry = pool[index]
    if entry["tag"] == CONSTANT_CLASSREF:
        entry = pool[entry["name"]]
    return entry["text"]


def read_export(path: pathlib.Path) -> dict:
    reader = Reader(path.read_bytes())
    if reader.u4() != MAGIC:
        raise ValueError(f"{path.name} is not an export file")
    minor, major = reader.u1(), reader.u1()
    pool = constant_pool(reader)
    package = pool[reader.u2()]
    # The referenced package table exists only from export format 2.3.
    if (major, minor) >= (2, 3):
        for _ in range(reader.u1()):
            reader.u2()
    classes = []
    for _ in range(reader.u1()):
        token = reader.u1()
        access_flags = reader.u2()
        name = text(pool, reader.u2())
        supers = [text(pool, reader.u2()) for _ in range(reader.u2())]
        interfaces = [text(pool, reader.u2()) for _ in range(reader.u1())]
        fields = []
        for _ in range(reader.u2()):
            field_token = reader.u1()
            field_flags = reader.u2()
            field_name = text(pool, reader.u2())
            descriptor = text(pool, reader.u2())
            attributes = []
            for _ in range(reader.u2()):
                # A ConstantValue attribute, JCVM section 5.10.1.
                attribute_name = text(pool, reader.u2())
                length = reader.u4()
                body = reader.take(length)
                if attribute_name == "ConstantValue" and len(body) == 2:
                    constant = pool[struct.unpack(">H", body)[0]]
                    attributes.append(constant.get("value"))
            fields.append({
                "token": field_token,
                "name": field_name,
                "descriptor": descriptor,
                "static": bool(field_flags & ACC_STATIC),
                "value": attributes[0] if attributes else None,
            })
        methods = []
        for _ in range(reader.u2()):
            method_token = reader.u1()
            method_flags = reader.u2()
            method_name = text(pool, reader.u2())
            descriptor = text(pool, reader.u2())
            methods.append({
                "token": method_token,
                "name": method_name,
                "descriptor": descriptor,
                "static": bool(method_flags & ACC_STATIC),
                # Static methods, constructors and private virtual methods share one token
                # namespace, JCVM section 4.3.7.4, and a constructor is reached by the same
                # constant type as a static call. The export file marks a constructor as an
                # instance method, so the namespace has to be worked out here.
                "static_namespace": bool(method_flags & ACC_STATIC) or method_name == "<init>",
            })
        if (major, minor) >= (2, 3):
            reader.u1()
        classes.append({
            "token": token,
            "name": name,
            "interface": bool(access_flags & ACC_INTERFACE),
            "supers": supers,
            "interfaces": interfaces,
            "fields": fields,
            "methods": methods,
        })
    if reader.at != len(reader.data):
        raise ValueError(f"{path.name} has {len(reader.data) - reader.at} trailing bytes")
    return {
        "aid": package["aid"],
        "name": text(pool, package["name"]).replace("/", "."),
        "version": package["version"],
        "export_format": f"{major}.{minor}",
        "classes": classes,
    }


def refresh(directory: pathlib.Path) -> dict:
    packages = []
    for path in sorted(directory.rglob("*.exp")):
        package = read_export(path)
        if package["aid"] in WANTED:
            packages.append(package)
    found = {package["aid"] for package in packages}
    missing = sorted(set(WANTED) - found)
    if missing:
        raise SystemExit("No export file for " + ", ".join(WANTED[aid] for aid in missing))
    packages.sort(key=lambda package: package["aid"])
    return {
        "source": "Java Card 3.0.5 export files, read from the development kit. Tokens are "
                  "what a CAP file uses to name an imported class, field or method.",
        "packages": packages,
    }


def identities(schema):
    classes = sorted({c["name"] for p in schema["packages"] for c in p["classes"]})
    methods = sorted({m["name"] for p in schema["packages"] for c in p["classes"] for m in c["methods"]})
    return {
        "PackageId": {p["name"]: p["name"].replace(".", "_") for p in schema["packages"]},
        "ClassId": {name: name.rsplit("/", 1)[-1].replace("$", "_") for name in classes},
        "MethodId": {name: "Constructor" if name == "<init>" else name for name in methods},
    }


def rust_ids(schema):
    lines = [f"// {BANNER}", "// Internal dispatch identities, never CAP tokens or persistent heap class words."]
    ids = identities(schema)
    for kind, names in ids.items():
        if len(names) > 256 or len(set(names.values())) != len(names):
            raise ValueError(f"ambiguous or oversized {kind}")
        lines += ["// Preserve the spellings from the Java Card exports.",
                  "#[allow(non_camel_case_types, clippy::upper_case_acronyms)]", "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
                  "#[repr(u8)]", f"pub enum {kind} {{"]
        lines += [f"    {name}," for name in names.values()]
        lines += ["}", ""]
    security = [name for name in ids["ClassId"] if name.startswith("javacard/security/")]
    first, last = (ids["ClassId"][name] for name in (security[0], security[-1]))
    keys = " | ".join(f"Self::{value}" for name, value in ids["ClassId"].items() if name.endswith("Key"))
    lines += ["impl ClassId {", "    pub fn is_security(self) -> bool {",
              f"        (self as u8) >= Self::{first} as u8 && (self as u8) <= Self::{last} as u8", "    }",
              "    pub fn is_key(self) -> bool {", f"        matches!(self, {keys})", "    }", "}", ""]
    return "\n".join(lines)


def rust_names(schema):
    lines = [f"// {BANNER}", "// Host diagnostics only; firmware uses the numeric identities.", "use super::jcvm_api_ids::*;", ""]
    for kind, names in identities(schema).items():
        lines += [f"impl {kind} {{", "    pub fn diagnostic_name(self) -> &'static str {", "        match self {"]
        lines += [f'            Self::{value} => "{name}",' for name, value in names.items()]
        lines += ["        }", "    }", "}", ""]
    return "\n".join(lines)


def rust(schema: dict) -> str:
    lines = [
        f"// {BANNER}",
        f"// Source: {schema['source']}",
        "pub use crate::jcvm_api_ids::{ClassId, MethodId, PackageId};",
        "",
        "/// One method an imported package declares, named by its token.",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub struct ApiMethod {",
        "    pub token: u8,",
        "    pub id: MethodId,",
        "    pub signature: Signature,",
        "    pub is_static: bool,",
        "    /// Whether the token belongs to the static namespace, which constructors",
        "    /// share with static methods even though they are instance methods.",
        "    pub static_token: bool,",
        "}",
        "",
        "/// One class an imported package declares.",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub struct ApiClass {",
        "    pub token: u8,",
        "    pub id: ClassId,",
        "    pub is_interface: bool,",
        "    /// Identities of the classes and interfaces this one extends, nearest first. A",
        "    /// catch clause matches any of them, which is how catching a supertype works.",
        "    pub supers: &'static [ClassId],",
        "    pub methods: &'static [ApiMethod],",
        "}",
        "",
        "/// One package an applet may import.",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub struct ApiPackage {",
        "    pub aid: &'static [u8],",
        "    pub id: PackageId,",
        "    /// The version the export file declares, which an import has to be satisfied by.",
        "    pub major: u8,",
        "    pub minor: u8,",
        "    pub classes: &'static [ApiClass],",
        "}",
        "",
    ]
    lines += ["#[derive(Clone, Copy, Debug, PartialEq, Eq)]", "pub struct Signature(u8);",
              "impl Signature {",
              "    pub fn empty_parameters(self) -> bool { self.0 & 1 != 0 }",
              "    pub fn init_vector(self) -> bool { self.0 & 2 != 0 }",
              "    pub fn init_mode(self) -> bool { self.0 & 4 != 0 }",
              "    pub fn key_pair_references(self) -> bool { self.0 & 8 != 0 }",
              "    pub fn combined_factory(self) -> bool { self.0 & 16 != 0 }", "}", ""]
    ids = identities(schema)
    for package in schema["packages"]:
        for klass in package["classes"]:
            symbol = f"{package['aid']}_{klass['token']}"
            supers = ", ".join(f"ClassId::{ids['ClassId'][name]}" for name in klass["supers"] + klass["interfaces"])
            lines.append(f"const SUPERS_{symbol}: [ClassId; {len(klass['supers']) + len(klass['interfaces'])}] = [{supers}];")
            lines.append(f"const METHODS_{symbol}: [ApiMethod; {len(klass['methods'])}] = [")
            for method in sorted(klass["methods"], key=lambda entry: entry["token"]):
                descriptor = method["descriptor"]
                signature = int(descriptor == "()V") | (int("[BSS" in descriptor) << 1) | (int(descriptor.endswith("B)V") or "SB" in descriptor) << 2)
                signature |= int(descriptor == "(Ljavacard/security/PublicKey;Ljavacard/security/PrivateKey;)V") << 3
                signature |= int(descriptor in ("(BBBZ)Ljavacard/security/Signature;", "(BBZ)Ljavacardx/crypto/Cipher;")) << 4
                lines.append(
                    f"    ApiMethod {{ token: {method['token']}, id: MethodId::{ids['MethodId'][method['name']]}, "
                    f"signature: Signature({signature}), is_static: {str(method['static']).lower()}, "
                    f"static_token: {str(method['static_namespace']).lower()} }},"
                )
            lines += ["];", ""]
        lines.append(f"const CLASSES_{package['aid']}: [ApiClass; {len(package['classes'])}] = [")
        for klass in sorted(package["classes"], key=lambda entry: entry["token"]):
            symbol = f"{package['aid']}_{klass['token']}"
            lines.append(
                f"    ApiClass {{ token: {klass['token']}, id: ClassId::{ids['ClassId'][klass['name']]}, "
                f"is_interface: {str(klass['interface']).lower()}, supers: &SUPERS_{symbol}, "
                f"methods: &METHODS_{symbol} }},"
            )
        lines += ["];", ""]
    lines.append(f"/// Every package this engine knows how to resolve an import against.")
    lines.append(f"pub const PACKAGES: [ApiPackage; {len(schema['packages'])}] = [")
    for package in schema["packages"]:
        aid = ", ".join(f"0x{package['aid'][at:at + 2].lower()}" for at in range(0, len(package["aid"]), 2))
        major, minor = package["version"].split(".")
        lines.append(
            f"    ApiPackage {{ aid: &[{aid}], id: PackageId::{ids['PackageId'][package['name']]}, "
            f"major: {major}, minor: {minor}, classes: &CLASSES_{package['aid']} }},"
        )
    lines += ["];", ""]
    return "\n".join(lines)


def markdown(schema: dict) -> str:
    lines = [
        "# Java Card API tokens",
        "",
        BANNER,
        "",
        f"Source: {schema['source']}",
        "",
        "A CAP file names an imported class, field or method by token. These are the "
        "tokens this engine resolves, and nothing outside this table can be called.",
        "",
        "Full method descriptors are in `format/jcvm-api.json` beside each token. "
        "Firmware dispatch uses generated numeric identities; readable names are "
        "compiled only for host diagnostics.",
        "",
    ]
    for package in schema["packages"]:
        lines += [
            f"## {package['name']} {package['version']}",
            "",
            f"AID `{package['aid']}`, export file format {package['export_format']}.",
            "",
            "| Class token | Class | Method token | Method | Static |",
            "| --- | --- | --- | --- | --- |",
        ]
        for klass in sorted(package["classes"], key=lambda entry: entry["token"]):
            if not klass["methods"]:
                lines.append(f"| {klass['token']} | `{klass['name']}` | | | |")
            for method in sorted(klass["methods"], key=lambda entry: entry["token"]):
                static = "yes" if method["static"] else "no"
                lines.append(
                    f"| {klass['token']} | `{klass['name']}` | {method['token']} | "
                    f"`{method['name']}` | {static} |"
                )
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--from-exp", type=pathlib.Path,
                       help="directory of export files to rebuild the table from")
    parser.add_argument("--check", action="store_true", help="verify the outputs are current")
    arguments = parser.parse_args()
    if arguments.from_exp:
        schema = refresh(arguments.from_exp)
        SOURCE.write_text(json.dumps(schema, indent=2) + "\n")
    else:
        schema = json.loads(SOURCE.read_text())
    outputs = {RUST: rust(schema), MARKDOWN: markdown(schema),
               RUST.with_name("jcvm_api_ids.rs"): rust_ids(schema),
               RUST.with_name("jcvm_api_names.rs"): rust_names(schema)}
    stale = [path for path, body in outputs.items()
             if not path.exists() or path.read_text() != body]
    if arguments.check:
        if stale:
            raise SystemExit("Stale generated files:\n  "
                             + "\n  ".join(str(path.relative_to(ROOT)) for path in stale))
    else:
        for path, body in outputs.items():
            path.write_text(body)
    methods = sum(len(klass["methods"]) for package in schema["packages"]
                  for klass in package["classes"])
    print(f"PASS: {len(schema['packages'])} imported packages, {methods} API methods")


if __name__ == "__main__":
    main()
