#!/usr/bin/env python3
"""Generate managed and device MC04 ABI tables from abi/mc04.toml."""
import argparse
import hashlib
import pathlib
import re
import subprocess
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "abi/mc04.toml"
CSHARP = ROOT / "managed/MicroCard.Build/Mc04Abi.g.cs"
RUST = ROOT / "crates/microcard-core/src/mc04_abi.rs"
NATIVE = ROOT / "crates/microcard-core/src/native_abi.rs"

TYPES = {"void", "bool", "int32", "byte[]", "int32[]"}
LOWERINGS = {"native", "current-context", "service", "storage-service"}
EFFECTS = {
    "none", "read", "random", "transactional", "transaction-control",
    "security-state", "irreversible",
}


def load():
    raw = SOURCE.read_bytes()
    data = tomllib.loads(raw.decode("utf-8"))
    abi = data["abi"]
    members = data["member"]
    profiles = set(abi["profiles"])
    seen = set()
    natives = {}
    for member in members:
        member.setdefault("assembly", abi["framework_assembly"])
        member.setdefault("namespace", abi["framework_namespace"])
        signature = (
            member["assembly"], member["namespace"], member["owner"],
            member["name"], member["kind"], tuple(member["parameters"]), member["result"],
        )
        if signature in seen:
            raise ValueError(f"duplicate ABI member: {signature}")
        seen.add(signature)
        if member["kind"] not in {"static", "instance"}:
            raise ValueError(f"invalid member kind: {member['kind']}")
        for value in [*member["parameters"], member["result"]]:
            if value not in TYPES and not re.fullmatch(r"(?:ref|enum):[A-Za-z_][A-Za-z0-9_.]*", value):
                raise ValueError(f"invalid ABI type: {value}")
        if member["lowering"] not in LOWERINGS:
            raise ValueError(f"invalid lowering: {member['lowering']}")
        if member["side_effect"] not in EFFECTS:
            raise ValueError(f"invalid side effect: {member['side_effect']}")
        if not set(member["profiles"]) <= profiles:
            raise ValueError(f"unknown profile on {member['owner']}.{member['name']}")
        if member["lowering"] == "native":
            native = member["native"]
            runtime_receiver = member.get("runtime_receiver", member["kind"] == "instance")
            shape = (len(member["parameters"]) + runtime_receiver,
                     member["result"] != "void", member["capability"])
            if native in natives:
                previous = natives[native]
                if previous[1:] != shape[1:]:
                    raise ValueError(f"conflicting native identity {native}")
                # A public instance service and a projected static BCL call may share
                # one device operation. The runtime accepts the larger service shape;
                # direct projections use the same implementation without a receiver.
                shape = (max(previous[0], shape[0]), shape[1], shape[2])
            natives[native] = shape
        elif "native" in member or "capability" in member:
            raise ValueError(f"non-native lowering has numeric identity: {member['owner']}.{member['name']}")
    return abi, members, natives, hashlib.sha256(raw).hexdigest()


def cs_string(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def csharp(abi, members, digest):
    lines = [
        "// Generated by scripts/generate_mc04_abi.py from abi/mc04.toml. Do not edit.",
        "using System;",
        "using System.Collections.Generic;",
        "",
        "namespace MicroCard.Build",
        "{",
        "    internal sealed class Mc04AbiMember",
        "    {",
        "        internal Mc04AbiMember(string assembly, string ns, string owner, string name,",
        "            bool instance, string[] parameters, string result, int capability,",
        "            string lowering, string sideEffect, string[] profiles)",
        "        {",
        "            Assembly = assembly; Namespace = ns; Owner = owner; Name = name;",
        "            Instance = instance; Parameters = parameters; Result = result;",
        "            Capability = capability; Lowering = lowering; SideEffect = sideEffect;",
        "            Profiles = profiles;",
        "        }",
        "        internal string Assembly { get; }",
        "        internal string Namespace { get; }",
        "        internal string Owner { get; }",
        "        internal string Name { get; }",
        "        internal bool Instance { get; }",
        "        internal string[] Parameters { get; }",
        "        internal string Result { get; }",
        "        internal int Capability { get; }",
        "        internal string Lowering { get; }",
        "        internal string SideEffect { get; }",
        "        internal string[] Profiles { get; }",
        "    }",
        "",
        "    internal static class Mc04Abi",
        "    {",
        f"        internal const string CatalogSha256 = {cs_string(digest)};",
        f"        internal const string FrameworkAssembly = {cs_string(abi['framework_assembly'])};",
        f"        internal const string FrameworkNamespace = {cs_string(abi['framework_namespace'])};",
        f"        internal const string FrameworkIdentitySha256 = {cs_string(abi['framework_identity_sha256'].upper())};",
        "        private static readonly Mc04AbiMember[] Members =",
        "        {",
    ]
    for member in members:
        parameters = ", ".join(cs_string(value) for value in member["parameters"])
        profiles = ", ".join(cs_string(value) for value in member["profiles"])
        parameter_array = f"new[] {{ {parameters} }}" if parameters else "Array.Empty<string>()"
        profile_array = f"new[] {{ {profiles} }}" if profiles else "Array.Empty<string>()"
        capability = member.get("capability", -1)
        lines += [
            "            new Mc04AbiMember(",
            f"                {cs_string(member['assembly'])}, {cs_string(member['namespace'])}, {cs_string(member['owner'])}, {cs_string(member['name'])},",
            f"                {str(member['kind'] == 'instance').lower()}, {parameter_array}, {cs_string(member['result'])}, {capability},",
            f"                {cs_string(member['lowering'])}, {cs_string(member['side_effect'])}, {profile_array}),",
        ]
    lines += [
        "        };",
        "",
        "        internal static bool ContainsName(string assembly, string ns, string owner, string name)",
        "        {",
        "            foreach (var member in Members)",
        "                if (member.Assembly == assembly && member.Namespace == ns &&",
        "                    member.Owner == owner && member.Name == name)",
        "                    return true;",
        "            return false;",
        "        }",
        "",
        "        internal static Mc04AbiMember Find(string assembly, string ns, string owner,",
        "            string name, bool instance, IReadOnlyList<string> parameters, string result)",
        "        {",
        "            foreach (var member in Members)",
        "            {",
        "                if (member.Assembly != assembly || member.Namespace != ns ||",
        "                    member.Owner != owner || member.Name != name ||",
        "                    member.Instance != instance || member.Result != result ||",
        "                    member.Parameters.Length != parameters.Count)",
        "                    continue;",
        "                var equal = true;",
        "                for (var index = 0; index < parameters.Count; index++)",
        "                    equal &= member.Parameters[index] == parameters[index];",
        "                if (equal) return member;",
        "            }",
        "            return null;",
        "        }",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def rust_type(value):
    if value == "void":
        return "None"
    names = {"bool": "Bool", "int32": "Int32", "byte[]": "ByteArray", "int32[]": "Int32Array"}
    if value in names:
        return f"Some(AbiType::{names[value]})"
    if value.startswith("enum:"):
        return "Some(AbiType::Int32)"
    return f'Some(AbiType::Reference("{value[4:]}"))'


def rust(abi, members, digest):
    lowerings = {
        "current-context": "CurrentDomain", "service": "DomainKeys",
        "storage-service": "DomainStorage",
    }
    effects = {name: "".join(part.title() for part in name.split("-")) for name in EFFECTS}
    lines = [
        "// Generated by scripts/generate_mc04_abi.py from abi/mc04.toml. Do not edit.",
        "#[allow(dead_code)]",
        f'pub const CATALOG_SHA256: &str = "{digest}";',
        f'pub const FRAMEWORK_ASSEMBLY: &str = "{abi["framework_assembly"]}";',
        f'pub const FRAMEWORK_NAMESPACE: &str = "{abi["framework_namespace"]}";',
        "pub const FRAMEWORK_HASH: &[u8] = &[",
    ]
    identity = bytes.fromhex(abi["framework_identity_sha256"])
    lines.append("    " + ", ".join(f"0x{value:02x}" for value in identity) + ",")
    lines += [
        "];",
        "",
        "#[allow(dead_code)]",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub enum AbiType {",
        "    Bool,",
        "    Int32,",
        "    ByteArray,",
        "    Int32Array,",
        "    Reference(&'static str),",
        "}",
        "",
        "#[allow(dead_code)]",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub enum Lowering {",
        "    Native(u8),",
        "    CurrentDomain,",
        "    DomainKeys,",
        "    DomainStorage,",
        "}",
        "",
        "#[allow(dead_code)]",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub enum SideEffect {",
        *[f"    {effects[name]}," for name in sorted(EFFECTS)],
        "}",
        "",
        "#[allow(dead_code)]",
        "#[derive(Clone, Copy, Debug)]",
        "pub struct Member {",
        "    pub assembly: &'static str,",
        "    pub namespace: &'static str,",
        "    pub owner: &'static str,",
        "    pub name: &'static str,",
        "    pub receiver: bool,",
        "    pub parameters: &'static [AbiType],",
        "    pub result: Option<AbiType>,",
        "    pub lowering: Lowering,",
        "    pub capability: Option<u8>,",
        "    pub side_effect: SideEffect,",
        "    pub profiles: &'static [&'static str],",
        "}",
        "",
        "pub const MEMBERS: &[Member] = &[",
    ]
    for member in members:
        params = ", ".join(rust_type(value)[5:-1] for value in member["parameters"])
        lowering = (f"Lowering::Native({member['native']})" if member["lowering"] == "native"
                    else f"Lowering::{lowerings[member['lowering']]}")
        capability = f"Some({member['capability']})" if "capability" in member else "None"
        profiles = ", ".join(f'"{value}"' for value in member["profiles"])
        lines += [
            "    Member {",
            f'        assembly: "{member["assembly"]}", namespace: "{member["namespace"]}",',
            f'        owner: "{member["owner"]}", name: "{member["name"]}", receiver: {str(member["kind"] == "instance").lower()},',
            f"        parameters: &[{params}], result: {rust_type(member['result'])},",
            f"        lowering: {lowering}, capability: {capability},",
            f"        side_effect: SideEffect::{effects[member['side_effect']]}, profiles: &[{profiles}],",
            "    },",
        ]
    lines += [
        "];",
        "",
        "pub fn named<'a>(assembly: &'a str, namespace: &'a str, owner: &'a str, name: &'a str)",
        "    -> impl Iterator<Item = &'static Member> + 'a",
        "{",
        "    MEMBERS.iter().filter(move |member| member.assembly == assembly &&",
        "        member.namespace == namespace && member.owner == owner && member.name == name)",
        "}",
        "",
    ]
    return "\n".join(lines)


def native_rust(abi, members, natives, digest):
    valid = sorted(natives)
    capabilities = sorted({shape[2] for shape in natives.values()})
    lines = [
        "// Generated by scripts/generate_mc04_abi.py from abi/mc04.toml. Do not edit.",
        "//! Stable native capability identifiers shared by package and domain validation.",
        "use crate::{Error, Result};",
        "",
        f'pub const CATALOG_SHA256: &str = "{digest}";',
        "",
        "/// Native operation IDs from the MC04 ABI catalog.",
        "pub mod id {",
    ]
    names = {}
    for member in members:
        if member["lowering"] != "native":
            continue
        native = member["native"]
        if native in names or member.get("projection"):
            continue
        stem = re.sub(r"(?<!^)(?=[A-Z])", "_", member["owner"]).upper()
        method = member["name"].removeprefix("get_")
        method = re.sub(r"(?<!^)(?=[A-Z])", "_", method).upper()
        names[native] = f"{stem}_{method}"
    emitted_names = set()
    for native, name in sorted(names.items()):
        if list(names.values()).count(name) > 1:
            member = next(m for m in members if m.get("native") == native)
            name += f"_{len(member['parameters'])}_ARGS"
        if name in emitted_names:
            raise ValueError(f"ambiguous native constant {name}")
        emitted_names.add(name)
        lines.append(f"    pub const {name}: u8 = {native};")
    lines += [
        "}",
        "",
        f"pub const CAPABILITIES: &[u8] = &[{', '.join(str(value) for value in capabilities)}];",
        "",
        "pub const fn valid_capability(id: u8) -> bool {",
        "    matches!(id, " + " | ".join(str(value) for value in capabilities) + ")",
        "}",
        "",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub struct Signature {",
        "    pub arguments: u8,",
        "    pub returns: bool,",
        "}",
        "",
        "pub const fn capability(id: u8) -> u8 {",
        "    match id {",
    ]
    for native, shape in sorted(natives.items()):
        if native != shape[2]:
            lines.append(f"        {native} => {shape[2]},")
    lines += ["        _ => id,", "    }", "}", "", "pub fn signature(id: u8) -> Result<Signature> {", "    let (arguments, returns) = match id {"]
    for native, (arguments, returns, _) in sorted(natives.items()):
        lines.append(f"        {native} => ({arguments}, {str(returns).lower()}),")
    lines += [
        "        _ => return Err(Error::Native),",
        "    };",
        "    Ok(Signature { arguments, returns })",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    #[test]",
        "    fn generated_capability_table_is_exact() {",
        f"        const VALID: &[u8] = &[{', '.join(str(value) for value in valid)}];",
        "        for id in 0..=u8::MAX {",
        "            assert_eq!(signature(id).is_ok(), VALID.contains(&id), \"capability {id}\");",
        "        }",
        "        for id in 0..=u8::MAX {",
        "            assert_eq!(valid_capability(id), CAPABILITIES.contains(&id), \"capability {id}\");",
        "        }",
        "        assert_eq!(capability(55), 46);",
        "        assert_eq!(capability(56), 47);",
        "        assert_eq!(capability(57), 48);",
        "        assert_eq!(capability(58), 46);",
        "        assert_eq!(capability(60), 46);",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def format_rust(content):
    process = subprocess.run(
        ["rustfmt", "--edition", "2021"], input=content, text=True,
        capture_output=True, check=False,
    )
    if process.returncode:
        raise RuntimeError(process.stderr.strip() or "rustfmt failed")
    return process.stdout


def generated_outputs():
    abi, members, natives, digest = load()
    return {
        CSHARP: csharp(abi, members, digest),
        RUST: format_rust(rust(abi, members, digest)),
        NATIVE: format_rust(native_rust(abi, members, natives, digest)),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in generated_outputs().items():
        content = content.rstrip() + "\n"
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        print("stale generated MC04 ABI files: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
