#!/usr/bin/env python3
"""Generate the public MC04 application API reference from its checked-in sources."""

import argparse
import pathlib
import re
import sys
import tomllib


ROOT = pathlib.Path(__file__).resolve().parents[1]
CATALOG = ROOT / "abi/mc04.toml"
FRAMEWORK = ROOT / "managed/MicroCard.Framework/Framework.cs"
FRAMEWORK_SOURCES = (FRAMEWORK, ROOT / "managed/MicroCard.Framework/Tlv.cs")
OUTPUT = ROOT / "docs/MC04_API.md"


def type_name(value: str) -> str:
    aliases = {
        "bool": "bool", "byte[]": "byte[]", "int32": "int", "int32[]": "int[]",
        "void": "void",
    }
    if value in aliases:
        return aliases[value]
    if value.startswith(("enum:", "ref:")):
        return value.rsplit(".", 1)[-1]
    raise ValueError(f"unknown ABI type: {value}")


def summaries() -> dict[str, str]:
    source = FRAMEWORK.read_text(encoding="utf-8")
    pattern = re.compile(
        r"/// <summary>(?P<summary>[^<]*)</summary>\s*"
        r"(?:\[[^\n]+\]\s*)*public (?:sealed |static )?(?:class|enum) (?P<name>\w+)",
    )
    return {
        match.group("name"): " ".join(match.group("summary").split())
        for match in pattern.finditer(source)
    }


def owner_body(source: str, owner: str) -> str | None:
    declaration = re.search(rf"public (?:sealed |static )?class {re.escape(owner)}\b", source)
    if declaration is None:
        return None
    start = source.find("{", declaration.end())
    depth = 0
    for index in range(start, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                return source[start + 1:index]
    raise ValueError(f"unclosed framework type: {owner}")


def parameter_names(owner: str, name: str, count: int) -> list[str]:
    for path in FRAMEWORK_SOURCES:
        body = owner_body(path.read_text(encoding="utf-8"), owner)
        if body is None:
            continue
        for match in re.finditer(
            rf"public\s+(?:static\s+)?[\w.\[\]<>?]+\s+{re.escape(name)}\s*\(([^)]*)\)",
            body,
        ):
            raw = match.group(1).strip()
            parameters = [] if not raw else [part.strip() for part in raw.split(",")]
            if len(parameters) == count:
                return [parameter.split("=")[0].split()[-1] for parameter in parameters]
    return [f"value{index}" for index in range(1, count + 1)]


def signature(member: dict) -> str:
    name = member["name"]
    result = type_name(member["result"])
    if name.startswith("get_") and not member["parameters"]:
        return f"{result} {name[4:]} {{ get; }}"
    names = parameter_names(member["owner"], name, len(member["parameters"]))
    parameters = ", ".join(
        f"{type_name(value)} {parameter}"
        for value, parameter in zip(member["parameters"], names)
    )
    prefix = "static " if member["kind"] == "static" else ""
    return f"{prefix}{result} {name}({parameters})"


def markdown() -> str:
    catalog = tomllib.loads(CATALOG.read_text(encoding="utf-8"))
    descriptions = summaries()
    groups: dict[str, list[dict]] = {}
    for member in catalog["member"]:
        if member.get("internal") or member.get("projection"):
            continue
        groups.setdefault(member["owner"], []).append(member)

    lines = [
        "# MC04 application API",
        "",
        "<!-- Generated by scripts/generate_mc04_api.py. Do not edit by hand. -->",
        "",
        "This reference lists the public calls that the MC04 converter recognizes. The",
        "member identities and lowering rules come from `abi/mc04.toml`; descriptions come",
        "from the framework XML documentation comments. Service receivers and typed enums",
        "lower directly to MC04 values and do not add a runtime assembly dependency.",
        "",
    ]
    for owner, members in groups.items():
        lines.extend((f"## `{owner}`", ""))
        if owner in descriptions:
            lines.extend((descriptions[owner], ""))
        lines.extend(("| Member | Effect | Capability |", "| --- | --- | ---: |"))
        for member in members:
            capability = str(member["capability"]) if "capability" in member else "None"
            lines.append(
                f"| `{signature(member)}` | `{member['side_effect']}` | {capability} |"
            )
        lines.append("")
    lines.extend((
        "## Transactions",
        "",
        "Explicit MC04 transactions use the supported `System.Transactions.TransactionScope`",
        "profile. The generated ABI keeps its lowering calls internal. See",
        "[transactions](TRANSACTIONS.md) for the exact lexical scope and failure behavior.",
        "",
        "## Authoring declarations",
        "",
        "`CardAssemblyAttribute`, persistent-storage declarations, dependency declarations,",
        "and dependency export policy are build metadata rather than runtime calls. See the",
        "[MC04 authoring guide](MC04_AUTHORING.md) for their use.",
        "",
    ))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = markdown()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            print(f"stale generated MC04 API reference: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            raise SystemExit(1)
    else:
        OUTPUT.write_text(generated, encoding="utf-8")
    print(f"PASS: generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
