#!/usr/bin/env python3
"""Generate host/device constants and the normative MC04 table appendix."""
import argparse, json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = ROOT / "format/mc04-schema.json"

def rust(schema):
    tables = schema["tables"]
    mask = sum(1 << table["id"] for table in tables)
    lines = [
        "// Generated by scripts/generate_mc04_schema.py. Do not edit.",
        f"pub const ALLOWED_TABLES: u64 = 0x{mask:016x};",
    ]
    for section in schema["sections"]:
        lines.append(f"pub const SECTION_{section['name'].upper()}: u8 = {section['id']};")
    for table in tables:
        upper = "".join(c if c.isalnum() else "_" for c in table["name"]).upper()
        lines += [
            f"pub const TABLE_{upper}: u8 = {table['id']};",
            f"pub const MAX_{upper}_ROWS: u16 = {table['max_rows']};",
        ]
    lines += [
        "pub fn max_rows(table: u8) -> Option<u16> {",
        "    Some(match table {",
    ]
    lines += [f"        {table['id']} => {table['max_rows']}," for table in tables]
    lines += ["        _ => return None,", "    })", "}", ""]
    lines += [
        "#[rustfmt::skip]",
        "pub fn row_width(table: u8, string_width: usize, blob_width: usize, rows: &[u16; 64]) -> Option<usize> {",
        "    Some(match table {",
    ]
    for table in tables:
        terms = []
        for _, kind in table["columns"]:
            if kind == "u16" or kind.startswith("coded:"): terms.append("2")
            elif kind == "u32": terms.append("4")
            elif kind == "string": terms.append("string_width")
            elif kind == "blob": terms.append("blob_width")
            elif kind.startswith("table:"):
                target = int(kind.split(":", 1)[1])
                terms.append(f"(if rows[{target}] <= 255 {{ 1 }} else {{ 2 }})")
            else: raise ValueError(kind)
        lines.append(f"        {table['id']} => " + " + ".join(terms) + ",")
    lines += ["        _ => return None,", "    })", "}", ""]
    return "\n".join(lines)

def csharp(schema):
    tables = schema["tables"]
    mask = sum(1 << table["id"] for table in tables)
    lines = [
        "// Generated by scripts/generate_mc04_schema.py. Do not edit.",
        "internal static class Mc04Schema",
        "{",
        f"    internal const ulong AllowedTables = 0x{mask:016X}UL;",
    ]
    for table in tables:
        lines.append(f"    internal const byte {table['name']} = {table['id']};")
        lines.append(f"    internal const ushort Max{table['name']}Rows = {table['max_rows']};")
    lines += ["}", ""]
    return "\n".join(lines)

def markdown(schema):
    lines = [
        "# MC04 metadata table appendix",
        "",
        "Generated from `format/mc04-schema.json`. Column order is normative. ECMA references name the retained logical table. Physical reductions are defined in `ASSEMBLY_FORMAT.md`.",
        "",
        "| ID | Table | Row limit | Columns | ECMA-335 |",
        "| ---: | --- | ---: | --- | --- |",
    ]
    for table in schema["tables"]:
        columns = ", ".join(f"`{name}:{kind}`" for name, kind in table["columns"])
        lines.append(f"| 0x{table['id']:02X} | {table['name']} | {table['max_rows']} | {columns} | {table['ecma']} |")
    lines += ["", "Index widths are canonical. Strings and blobs use u8 through offset 255, otherwise u16. Table-list indices use u8 through row 255, otherwise u16. `coded_u16` is a bounded ECMA coded index with the original tag assignment.", ""]
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = json.loads(SOURCE.read_text())
    outputs = {
        ROOT / "crates/microcard-core/src/mc04_schema.rs": rust(schema),
        ROOT / "managed/MicroCard.Tool/Mc04Schema.g.cs": csharp(schema),
        ROOT / "docs/MC04_TABLES.md": markdown(schema),
    }
    stale = []
    for path, content in outputs.items():
        content = content.rstrip() + "\n"
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        print("stale generated MC04 files: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
